//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 8d866005b6bc
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Model architecture information.
    /// </summary>
    public class Architecture
    {
        [JsonProperty("tokenizer", NullValueHandling = NullValueHandling.Include)]
        public Tokenizer? Tokenizer { get; set; }

        /// <summary>
        /// Instruction format type.
        /// </summary>
        [JsonProperty("instruct_type", NullValueHandling = NullValueHandling.Include)]
        public InstructType? InstructType { get; set; }

        /// <summary>
        /// Primary modality of the model.
        /// </summary>
        [JsonProperty("modality", NullValueHandling = NullValueHandling.Include)]
        public string? Modality { get; set; }

        /// <summary>
        /// Supported input modalities.
        /// </summary>
        [JsonProperty("input_modalities")]
        public List<InputModality> InputModalities { get; set; } = default!;

        /// <summary>
        /// Supported output modalities.
        /// </summary>
        [JsonProperty("output_modalities")]
        public List<OutputModality> OutputModalities { get; set; } = default!;
    }
}