//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: db109d6b91a3
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// Assistant message for requests and responses.
    /// </summary>
    public class AssistantMessage
    {
        [JsonProperty("role")]
        public AssistantMessageRole Role { get; set; } = default!;

        /// <summary>
        /// Assistant message content.
        /// </summary>
        [JsonProperty("content", NullValueHandling = NullValueHandling.Include)]
        public AssistantMessageContent? Content { get; set; } = null;

        /// <summary>
        /// Optional name for the assistant.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Tool calls made by the assistant.
        /// </summary>
        [JsonProperty("tool_calls")]
        public List<ChatMessageToolCall>? ToolCalls { get; set; }

        /// <summary>
        /// Refusal message if content was refused.
        /// </summary>
        [JsonProperty("refusal")]
        public string? Refusal { get; set; } = null;

        /// <summary>
        /// Reasoning output.
        /// </summary>
        [JsonProperty("reasoning")]
        public string? Reasoning { get; set; } = null;

        /// <summary>
        /// Reasoning details for extended thinking models.
        /// </summary>
        [JsonProperty("reasoning_details")]
        public List<ReasoningDetailUnion>? ReasoningDetails { get; set; }

        /// <summary>
        /// Generated images from image generation models.
        /// </summary>
        [JsonProperty("images")]
        public List<AssistantMessageImages>? Images { get; set; }
    }
}