//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: c39ee8ed1401
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ChatCompletionFinishReason : IEquatable<ChatCompletionFinishReason>
    {
        public static readonly ChatCompletionFinishReason ToolCalls = new ChatCompletionFinishReason("tool_calls");
        public static readonly ChatCompletionFinishReason Stop = new ChatCompletionFinishReason("stop");
        public static readonly ChatCompletionFinishReason Length = new ChatCompletionFinishReason("length");
        public static readonly ChatCompletionFinishReason ContentFilter = new ChatCompletionFinishReason("content_filter");
        public static readonly ChatCompletionFinishReason Error = new ChatCompletionFinishReason("error");

        private static readonly Dictionary<string, ChatCompletionFinishReason> _knownValues =
            new Dictionary<string, ChatCompletionFinishReason>() {
                ["tool_calls"] = ToolCalls,
                ["stop"] = Stop,
                ["length"] = Length,
                ["content_filter"] = ContentFilter,
                ["error"] = Error
            };

        private static readonly ConcurrentDictionary<string, ChatCompletionFinishReason> _values =
            new ConcurrentDictionary<string, ChatCompletionFinishReason>(_knownValues);

        private ChatCompletionFinishReason(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ChatCompletionFinishReason Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ChatCompletionFinishReason(value));
        }

        public static implicit operator ChatCompletionFinishReason(string value) => Of(value);
        public static implicit operator string(ChatCompletionFinishReason chatcompletionfinishreason) => chatcompletionfinishreason.Value;

        public static ChatCompletionFinishReason[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ChatCompletionFinishReason);

        public bool Equals(ChatCompletionFinishReason? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}