//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: d7d73657c030
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    public class ChatMessageTokenLogprobTopLogprob
    {
        [JsonProperty("token")]
        public string Token { get; set; } = default!;

        [JsonProperty("logprob")]
        public double Logprob { get; set; } = default!;

        [JsonProperty("bytes", NullValueHandling = NullValueHandling.Include)]
        public List<double>? Bytes { get; set; }
    }
}