//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 4a59fd6c6d9c
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The provider sorting strategy (price, throughput, latency).
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ChatGenerationParamsBy : IEquatable<ChatGenerationParamsBy>
    {
        public static readonly ChatGenerationParamsBy Price = new ChatGenerationParamsBy("price");
        public static readonly ChatGenerationParamsBy Throughput = new ChatGenerationParamsBy("throughput");
        public static readonly ChatGenerationParamsBy Latency = new ChatGenerationParamsBy("latency");

        private static readonly Dictionary<string, ChatGenerationParamsBy> _knownValues =
            new Dictionary<string, ChatGenerationParamsBy>() {
                ["price"] = Price,
                ["throughput"] = Throughput,
                ["latency"] = Latency
            };

        private static readonly ConcurrentDictionary<string, ChatGenerationParamsBy> _values =
            new ConcurrentDictionary<string, ChatGenerationParamsBy>(_knownValues);

        private ChatGenerationParamsBy(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ChatGenerationParamsBy Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ChatGenerationParamsBy(value));
        }

        public static implicit operator ChatGenerationParamsBy(string value) => Of(value);
        public static implicit operator string(ChatGenerationParamsBy chatgenerationparamsby) => chatgenerationparamsby.Value;

        public static ChatGenerationParamsBy[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ChatGenerationParamsBy);

        public bool Equals(ChatGenerationParamsBy? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}