//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 2d0760fc24fe
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Token usage statistics.
    /// </summary>
    public class ChatGenerationTokenUsage
    {
        /// <summary>
        /// Number of tokens in the completion.
        /// </summary>
        [JsonProperty("completion_tokens")]
        public double CompletionTokens { get; set; } = default!;

        /// <summary>
        /// Number of tokens in the prompt.
        /// </summary>
        [JsonProperty("prompt_tokens")]
        public double PromptTokens { get; set; } = default!;

        /// <summary>
        /// Total number of tokens.
        /// </summary>
        [JsonProperty("total_tokens")]
        public double TotalTokens { get; set; } = default!;

        /// <summary>
        /// Detailed completion token usage.
        /// </summary>
        [JsonProperty("completion_tokens_details")]
        public CompletionTokensDetails? CompletionTokensDetails { get; set; } = null;

        /// <summary>
        /// Detailed prompt token usage.
        /// </summary>
        [JsonProperty("prompt_tokens_details")]
        public PromptTokensDetails? PromptTokensDetails { get; set; } = null;
    }
}