//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 4ab1e787558d
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Image detail level for vision models.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ChatMessageContentItemImageDetail : IEquatable<ChatMessageContentItemImageDetail>
    {
        public static readonly ChatMessageContentItemImageDetail Auto = new ChatMessageContentItemImageDetail("auto");
        public static readonly ChatMessageContentItemImageDetail Low = new ChatMessageContentItemImageDetail("low");
        public static readonly ChatMessageContentItemImageDetail High = new ChatMessageContentItemImageDetail("high");

        private static readonly Dictionary<string, ChatMessageContentItemImageDetail> _knownValues =
            new Dictionary<string, ChatMessageContentItemImageDetail>() {
                ["auto"] = Auto,
                ["low"] = Low,
                ["high"] = High
            };

        private static readonly ConcurrentDictionary<string, ChatMessageContentItemImageDetail> _values =
            new ConcurrentDictionary<string, ChatMessageContentItemImageDetail>(_knownValues);

        private ChatMessageContentItemImageDetail(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ChatMessageContentItemImageDetail Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ChatMessageContentItemImageDetail(value));
        }

        public static implicit operator ChatMessageContentItemImageDetail(string value) => Of(value);
        public static implicit operator string(ChatMessageContentItemImageDetail chatmessagecontentitemimagedetail) => chatmessagecontentitemimagedetail.Value;

        public static ChatMessageContentItemImageDetail[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ChatMessageContentItemImageDetail);

        public bool Equals(ChatMessageContentItemImageDetail? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}