//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7e93452c6e2c
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// Streaming chat completion chunk.
    /// </summary>
    public class ChatStreamingResponseChunk
    {
        /// <summary>
        /// Unique chunk identifier.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// List of streaming chunk choices.
        /// </summary>
        [JsonProperty("choices")]
        public List<ChatStreamingChoice> Choices { get; set; } = default!;

        /// <summary>
        /// Unix timestamp of creation.
        /// </summary>
        [JsonProperty("created")]
        public double Created { get; set; } = default!;

        /// <summary>
        /// Model used for completion.
        /// </summary>
        [JsonProperty("model")]
        public string Model { get; set; } = default!;

        [JsonProperty("object")]
        public ChatStreamingResponseChunkObject Object { get; set; } = default!;

        /// <summary>
        /// System fingerprint.
        /// </summary>
        [JsonProperty("system_fingerprint")]
        public string? SystemFingerprint { get; set; } = null;

        /// <summary>
        /// Error information.
        /// </summary>
        [JsonProperty("error")]
        public Error? Error { get; set; }

        /// <summary>
        /// Token usage statistics.
        /// </summary>
        [JsonProperty("usage")]
        public ChatGenerationTokenUsage? Usage { get; set; }
    }
}