//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 38e43c1932fb
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;

    /// <summary>
    /// Video input content part (legacy format - deprecated).
    /// </summary>
    [Obsolete("This will be removed in a future release, please migrate away from it as soon as possible")]
    public class ChatMessageContentItemVideoLegacy
    {
        [JsonProperty("type")]
        public ChatMessageContentItemVideoLegacyType Type { get; set; } = default!;

        /// <summary>
        /// Video input object.
        /// </summary>
        [JsonProperty("video_url")]
        public VideoInput VideoUrl { get; set; } = default!;
    }
}