//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 4318701cd49c
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ChatGenerationParamsImageConfigType
    {
        private ChatGenerationParamsImageConfigType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ChatGenerationParamsImageConfigType Str
        {
            get {
                return new ChatGenerationParamsImageConfigType("str");
            }
        }

        public static ChatGenerationParamsImageConfigType Number
        {
            get {
                return new ChatGenerationParamsImageConfigType("number");
            }
        }

        public static ChatGenerationParamsImageConfigType ArrayOfAny
        {
            get {
                return new ChatGenerationParamsImageConfigType("arrayOfAny");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ChatGenerationParamsImageConfigType v)
        {
            return v.Value;
        }
        public static ChatGenerationParamsImageConfigType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "number":
                    return Number;
                case "arrayOfAny":
                    return ArrayOfAny;
                default:
                    throw new ArgumentException("Invalid value for ChatGenerationParamsImageConfigType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ChatGenerationParamsImageConfigType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ChatGenerationParamsImageConfig.ChatGenerationParamsImageConfigConverter))]
    public class ChatGenerationParamsImageConfig
    {
        public ChatGenerationParamsImageConfig(ChatGenerationParamsImageConfigType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<object?>? ArrayOfAny { get; set; }

        public ChatGenerationParamsImageConfigType Type { get; set; }
        public static ChatGenerationParamsImageConfig CreateStr(string str)
        {
            ChatGenerationParamsImageConfigType typ = ChatGenerationParamsImageConfigType.Str;

            ChatGenerationParamsImageConfig res = new ChatGenerationParamsImageConfig(typ);
            res.Str = str;
            return res;
        }
        public static ChatGenerationParamsImageConfig CreateNumber(double number)
        {
            ChatGenerationParamsImageConfigType typ = ChatGenerationParamsImageConfigType.Number;

            ChatGenerationParamsImageConfig res = new ChatGenerationParamsImageConfig(typ);
            res.Number = number;
            return res;
        }
        public static ChatGenerationParamsImageConfig CreateArrayOfAny(List<object?> arrayOfAny)
        {
            ChatGenerationParamsImageConfigType typ = ChatGenerationParamsImageConfigType.ArrayOfAny;

            ChatGenerationParamsImageConfig res = new ChatGenerationParamsImageConfig(typ);
            res.ArrayOfAny = arrayOfAny;
            return res;
        }

        public class ChatGenerationParamsImageConfigConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ChatGenerationParamsImageConfig);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new ChatGenerationParamsImageConfig(ChatGenerationParamsImageConfigType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new ChatGenerationParamsImageConfig(ChatGenerationParamsImageConfigType.Number) {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new ChatGenerationParamsImageConfig(ChatGenerationParamsImageConfigType.ArrayOfAny) {
                        ArrayOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<object?>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<object?>), new ChatGenerationParamsImageConfig(ChatGenerationParamsImageConfigType.ArrayOfAny), "ArrayOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ChatGenerationParamsImageConfig res = (ChatGenerationParamsImageConfig)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.ArrayOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAny));
                    return;
                }
            }
        }
    }
}