//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 6c595e2a3ca1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Video input content part.
    /// </summary>
    public class ChatMessageContentItemVideo
    {
        [JsonProperty("type")]
        public ChatMessageContentItemVideoType Type { get; set; } = default!;

        /// <summary>
        /// Video input object.
        /// </summary>
        [JsonProperty("video_url")]
        public VideoInput VideoUrl { get; set; } = default!;
    }
}