//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 515e4f5b6cbf
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ChatMessageContentItemType
    {
        private ChatMessageContentItemType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ChatMessageContentItemType ChatMessageContentItemText
        {
            get {
                return new ChatMessageContentItemType("ChatMessageContentItemText");
            }
        }

        public static ChatMessageContentItemType ChatMessageContentItemImage
        {
            get {
                return new ChatMessageContentItemType("ChatMessageContentItemImage");
            }
        }

        public static ChatMessageContentItemType ChatMessageContentItemAudio
        {
            get {
                return new ChatMessageContentItemType("ChatMessageContentItemAudio");
            }
        }

        public static ChatMessageContentItemType ChatMessageContentItem1
        {
            get {
                return new ChatMessageContentItemType("ChatMessageContentItem_1");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ChatMessageContentItemType v)
        {
            return v.Value;
        }
        public static ChatMessageContentItemType FromString(string v)
        {
            switch (v)
            {
                case "ChatMessageContentItemText":
                    return ChatMessageContentItemText;
                case "ChatMessageContentItemImage":
                    return ChatMessageContentItemImage;
                case "ChatMessageContentItemAudio":
                    return ChatMessageContentItemAudio;
                case "ChatMessageContentItem_1":
                    return ChatMessageContentItem1;
                default:
                    throw new ArgumentException("Invalid value for ChatMessageContentItemType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ChatMessageContentItemType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Content part for chat completion messages.
    /// </summary>
    [JsonConverter(typeof(ChatMessageContentItem.ChatMessageContentItemConverter))]
    public class ChatMessageContentItem
    {
        public ChatMessageContentItem(ChatMessageContentItemType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ChatMessageContentItemText? ChatMessageContentItemText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ChatMessageContentItemImage? ChatMessageContentItemImage { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ChatMessageContentItemAudio? ChatMessageContentItemAudio { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ChatMessageContentItem1? ChatMessageContentItem1 { get; set; }

        public ChatMessageContentItemType Type { get; set; }
        public static ChatMessageContentItem CreateChatMessageContentItemText(ChatMessageContentItemText chatMessageContentItemText)
        {
            ChatMessageContentItemType typ = ChatMessageContentItemType.ChatMessageContentItemText;

            ChatMessageContentItem res = new ChatMessageContentItem(typ);
            res.ChatMessageContentItemText = chatMessageContentItemText;
            return res;
        }
        public static ChatMessageContentItem CreateChatMessageContentItemImage(ChatMessageContentItemImage chatMessageContentItemImage)
        {
            ChatMessageContentItemType typ = ChatMessageContentItemType.ChatMessageContentItemImage;

            ChatMessageContentItem res = new ChatMessageContentItem(typ);
            res.ChatMessageContentItemImage = chatMessageContentItemImage;
            return res;
        }
        public static ChatMessageContentItem CreateChatMessageContentItemAudio(ChatMessageContentItemAudio chatMessageContentItemAudio)
        {
            ChatMessageContentItemType typ = ChatMessageContentItemType.ChatMessageContentItemAudio;

            ChatMessageContentItem res = new ChatMessageContentItem(typ);
            res.ChatMessageContentItemAudio = chatMessageContentItemAudio;
            return res;
        }
        public static ChatMessageContentItem CreateChatMessageContentItem1(ChatMessageContentItem1 chatMessageContentItem1)
        {
            ChatMessageContentItemType typ = ChatMessageContentItemType.ChatMessageContentItem1;

            ChatMessageContentItem res = new ChatMessageContentItem(typ);
            res.ChatMessageContentItem1 = chatMessageContentItem1;
            return res;
        }

        public class ChatMessageContentItemConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ChatMessageContentItem);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItemImage) {
                        ChatMessageContentItemImage = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ChatMessageContentItemImage>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ChatMessageContentItemImage), new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItemImage), "ChatMessageContentItemImage"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItemAudio) {
                        ChatMessageContentItemAudio = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ChatMessageContentItemAudio>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ChatMessageContentItemAudio), new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItemAudio), "ChatMessageContentItemAudio"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItemText) {
                        ChatMessageContentItemText = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ChatMessageContentItemText>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ChatMessageContentItemText), new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItemText), "ChatMessageContentItemText"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItem1) {
                        ChatMessageContentItem1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ChatMessageContentItem1>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ChatMessageContentItem1), new ChatMessageContentItem(ChatMessageContentItemType.ChatMessageContentItem1), "ChatMessageContentItem1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ChatMessageContentItem res = (ChatMessageContentItem)value;

                if (res.ChatMessageContentItemText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ChatMessageContentItemText));
                    return;
                }

                if (res.ChatMessageContentItemImage != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ChatMessageContentItemImage));
                    return;
                }

                if (res.ChatMessageContentItemAudio != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ChatMessageContentItemAudio));
                    return;
                }

                if (res.ChatMessageContentItem1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ChatMessageContentItem1));
                    return;
                }
            }
        }
    }
}