//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0c7b9e9f26b4
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The provider sorting strategy (price, throughput, latency).
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ChatGenerationParamsProviderSort : IEquatable<ChatGenerationParamsProviderSort>
    {
        public static readonly ChatGenerationParamsProviderSort Price = new ChatGenerationParamsProviderSort("price");
        public static readonly ChatGenerationParamsProviderSort Throughput = new ChatGenerationParamsProviderSort("throughput");
        public static readonly ChatGenerationParamsProviderSort Latency = new ChatGenerationParamsProviderSort("latency");

        private static readonly Dictionary<string, ChatGenerationParamsProviderSort> _knownValues =
            new Dictionary<string, ChatGenerationParamsProviderSort>() {
                ["price"] = Price,
                ["throughput"] = Throughput,
                ["latency"] = Latency
            };

        private static readonly ConcurrentDictionary<string, ChatGenerationParamsProviderSort> _values =
            new ConcurrentDictionary<string, ChatGenerationParamsProviderSort>(_knownValues);

        private ChatGenerationParamsProviderSort(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ChatGenerationParamsProviderSort Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ChatGenerationParamsProviderSort(value));
        }

        public static implicit operator ChatGenerationParamsProviderSort(string value) => Of(value);
        public static implicit operator string(ChatGenerationParamsProviderSort chatgenerationparamsprovidersort) => chatgenerationparamsprovidersort.Value;

        public static ChatGenerationParamsProviderSort[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ChatGenerationParamsProviderSort);

        public bool Equals(ChatGenerationParamsProviderSort? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}