//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: bee6a7b99d98
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Partitioning strategy for sorting: "model" (default) groups endpoints by model before sorting (fallback models remain fallbacks), "none" sorts all endpoints together regardless of model.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ChatGenerationParamsPartition : IEquatable<ChatGenerationParamsPartition>
    {
        public static readonly ChatGenerationParamsPartition Model = new ChatGenerationParamsPartition("model");
        public static readonly ChatGenerationParamsPartition None = new ChatGenerationParamsPartition("none");

        private static readonly Dictionary<string, ChatGenerationParamsPartition> _knownValues =
            new Dictionary<string, ChatGenerationParamsPartition>() {
                ["model"] = Model,
                ["none"] = None
            };

        private static readonly ConcurrentDictionary<string, ChatGenerationParamsPartition> _values =
            new ConcurrentDictionary<string, ChatGenerationParamsPartition>(_knownValues);

        private ChatGenerationParamsPartition(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ChatGenerationParamsPartition Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ChatGenerationParamsPartition(value));
        }

        public static implicit operator ChatGenerationParamsPartition(string value) => Of(value);
        public static implicit operator string(ChatGenerationParamsPartition chatgenerationparamspartition) => chatgenerationparamspartition.Value;

        public static ChatGenerationParamsPartition[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ChatGenerationParamsPartition);

        public bool Equals(ChatGenerationParamsPartition? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}