//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7db7ed8cfbb7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Data collection setting. If no available model provider meets the requirement, your request will return an error.<br/>
    /// - allow: (default) allow providers which store user data non-transiently and may train on it<br/>
    /// <br/>
    /// - deny: use only providers which do not collect user data.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class DataCollection : IEquatable<DataCollection>
    {
        public static readonly DataCollection Deny = new DataCollection("deny");
        public static readonly DataCollection Allow = new DataCollection("allow");

        private static readonly Dictionary<string, DataCollection> _knownValues =
            new Dictionary<string, DataCollection>() {
                ["deny"] = Deny,
                ["allow"] = Allow
            };

        private static readonly ConcurrentDictionary<string, DataCollection> _values =
            new ConcurrentDictionary<string, DataCollection>(_knownValues);

        private DataCollection(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static DataCollection Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new DataCollection(value));
        }

        public static implicit operator DataCollection(string value) => Of(value);
        public static implicit operator string(DataCollection datacollection) => datacollection.Value;

        public static DataCollection[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as DataCollection);

        public bool Equals(DataCollection? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}