//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 1c99b3f5eec1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Model count data.
    /// </summary>
    public class Data
    {
        /// <summary>
        /// Total number of available models.
        /// </summary>
        [JsonProperty("count")]
        public double Count { get; set; } = default!;
    }
}