//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: f7ac0c9c5c83
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Debug options for inspecting request transformations (streaming only).
    /// </summary>
    public class DebugOptions
    {
        /// <summary>
        /// If true, includes the transformed upstream request body in a debug chunk at the start of the stream. Only works with streaming mode.
        /// </summary>
        [JsonProperty("echo_upstream_body")]
        public bool? EchoUpstreamBody { get; set; }
    }
}