//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 2d4ed4a354e4
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Default parameters for this model.
    /// </summary>
    public class DefaultParameters
    {
        [JsonProperty("temperature")]
        public double? Temperature { get; set; } = null;

        [JsonProperty("top_p")]
        public double? TopP { get; set; } = null;

        [JsonProperty("frequency_penalty")]
        public double? FrequencyPenalty { get; set; } = null;
    }
}