//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0c9c560432f1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class EndpointStatus : IEquatable<EndpointStatus>
    {
        public static readonly EndpointStatus Zero = new EndpointStatus(0);
        public static readonly EndpointStatus Minus1 = new EndpointStatus(-1);
        public static readonly EndpointStatus Minus2 = new EndpointStatus(-2);
        public static readonly EndpointStatus Minus3 = new EndpointStatus(-3);
        public static readonly EndpointStatus Minus5 = new EndpointStatus(-5);
        public static readonly EndpointStatus Minus10 = new EndpointStatus(-10);

        private static readonly Dictionary<long, EndpointStatus> _knownValues =
            new Dictionary<long, EndpointStatus>() {
                [0] = Zero,
                [-1] = Minus1,
                [-2] = Minus2,
                [-3] = Minus3,
                [-5] = Minus5,
                [-10] = Minus10
            };

        private static readonly ConcurrentDictionary<long, EndpointStatus> _values =
            new ConcurrentDictionary<long, EndpointStatus>(_knownValues);

        private EndpointStatus(long value)
        {
            Value = value;
        }

        public long Value { get; }

        public static EndpointStatus Of(long value)
        {
            return _values.GetOrAdd(value,
                                    _ => new EndpointStatus(value));
        }

        public static implicit operator EndpointStatus(long value) => Of(value);
        public static implicit operator long(EndpointStatus endpointstatus) => endpointstatus.Value;

        public static EndpointStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as EndpointStatus);

        public bool Equals(EndpointStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}