//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 93e16d697595
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// JSON Schema configuration object.
    /// </summary>
    public class JSONSchemaConfig
    {
        /// <summary>
        /// Schema name (a-z, A-Z, 0-9, underscores, dashes, max 64 chars).
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Schema description for the model.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// JSON Schema object.
        /// </summary>
        [JsonProperty("schema")]
        public Dictionary<string, object?>? Schema { get; set; }

        /// <summary>
        /// Enable strict schema adherence.
        /// </summary>
        [JsonProperty("strict")]
        public bool? Strict { get; set; } = null;
    }
}