//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: dcd109657ef5
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// List of available endpoints for a model.
    /// </summary>
    public class ListEndpointsResponse
    {
        /// <summary>
        /// Unique identifier for the model.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Display name of the model.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Unix timestamp of when the model was created.
        /// </summary>
        [JsonProperty("created")]
        public double Created { get; set; } = default!;

        /// <summary>
        /// Description of the model.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; } = default!;

        [JsonProperty("architecture")]
        public Architecture Architecture { get; set; } = default!;

        /// <summary>
        /// List of available endpoints for this model.
        /// </summary>
        [JsonProperty("endpoints")]
        public List<PublicEndpoint> Endpoints { get; set; } = default!;
    }
}