//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: d67fe26c3793
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class Modality : IEquatable<Modality>
    {
        public static readonly Modality Text = new Modality("text");
        public static readonly Modality Image = new Modality("image");

        private static readonly Dictionary<string, Modality> _knownValues =
            new Dictionary<string, Modality>() {
                ["text"] = Text,
                ["image"] = Image
            };

        private static readonly ConcurrentDictionary<string, Modality> _values =
            new ConcurrentDictionary<string, Modality>(_knownValues);

        private Modality(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Modality Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new Modality(value));
        }

        public static implicit operator Modality(string value) => Of(value);
        public static implicit operator string(Modality modality) => modality.Value;

        public static Modality[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Modality);

        public bool Equals(Modality? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}