//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: eae0e8d0f7d8
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Instruction format type.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ModelArchitectureInstructType : IEquatable<ModelArchitectureInstructType>
    {
        public static readonly ModelArchitectureInstructType None = new ModelArchitectureInstructType("none");
        public static readonly ModelArchitectureInstructType Airoboros = new ModelArchitectureInstructType("airoboros");
        public static readonly ModelArchitectureInstructType Alpaca = new ModelArchitectureInstructType("alpaca");
        public static readonly ModelArchitectureInstructType AlpacaModif = new ModelArchitectureInstructType("alpaca-modif");
        public static readonly ModelArchitectureInstructType Chatml = new ModelArchitectureInstructType("chatml");
        public static readonly ModelArchitectureInstructType Claude = new ModelArchitectureInstructType("claude");
        public static readonly ModelArchitectureInstructType CodeLlama = new ModelArchitectureInstructType("code-llama");
        public static readonly ModelArchitectureInstructType Gemma = new ModelArchitectureInstructType("gemma");
        public static readonly ModelArchitectureInstructType Llama2 = new ModelArchitectureInstructType("llama2");
        public static readonly ModelArchitectureInstructType Llama3 = new ModelArchitectureInstructType("llama3");
        public static readonly ModelArchitectureInstructType Mistral = new ModelArchitectureInstructType("mistral");
        public static readonly ModelArchitectureInstructType Nemotron = new ModelArchitectureInstructType("nemotron");
        public static readonly ModelArchitectureInstructType Neural = new ModelArchitectureInstructType("neural");
        public static readonly ModelArchitectureInstructType Openchat = new ModelArchitectureInstructType("openchat");
        public static readonly ModelArchitectureInstructType Phi3 = new ModelArchitectureInstructType("phi3");
        public static readonly ModelArchitectureInstructType Rwkv = new ModelArchitectureInstructType("rwkv");
        public static readonly ModelArchitectureInstructType Vicuna = new ModelArchitectureInstructType("vicuna");
        public static readonly ModelArchitectureInstructType Zephyr = new ModelArchitectureInstructType("zephyr");
        public static readonly ModelArchitectureInstructType DeepseekR1 = new ModelArchitectureInstructType("deepseek-r1");
        public static readonly ModelArchitectureInstructType DeepseekV31 = new ModelArchitectureInstructType("deepseek-v3.1");
        public static readonly ModelArchitectureInstructType Qwq = new ModelArchitectureInstructType("qwq");
        public static readonly ModelArchitectureInstructType Qwen3 = new ModelArchitectureInstructType("qwen3");

        private static readonly Dictionary<string, ModelArchitectureInstructType> _knownValues =
            new Dictionary<string, ModelArchitectureInstructType>() {
                ["none"] = None,
                ["airoboros"] = Airoboros,
                ["alpaca"] = Alpaca,
                ["alpaca-modif"] = AlpacaModif,
                ["chatml"] = Chatml,
                ["claude"] = Claude,
                ["code-llama"] = CodeLlama,
                ["gemma"] = Gemma,
                ["llama2"] = Llama2,
                ["llama3"] = Llama3,
                ["mistral"] = Mistral,
                ["nemotron"] = Nemotron,
                ["neural"] = Neural,
                ["openchat"] = Openchat,
                ["phi3"] = Phi3,
                ["rwkv"] = Rwkv,
                ["vicuna"] = Vicuna,
                ["zephyr"] = Zephyr,
                ["deepseek-r1"] = DeepseekR1,
                ["deepseek-v3.1"] = DeepseekV31,
                ["qwq"] = Qwq,
                ["qwen3"] = Qwen3
            };

        private static readonly ConcurrentDictionary<string, ModelArchitectureInstructType> _values =
            new ConcurrentDictionary<string, ModelArchitectureInstructType>(_knownValues);

        private ModelArchitectureInstructType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ModelArchitectureInstructType Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ModelArchitectureInstructType(value));
        }

        public static implicit operator ModelArchitectureInstructType(string value) => Of(value);
        public static implicit operator string(ModelArchitectureInstructType modelarchitectureinstructtype) => modelarchitectureinstructtype.Value;

        public static ModelArchitectureInstructType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ModelArchitectureInstructType);

        public bool Equals(ModelArchitectureInstructType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}