//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 28c46850ad0e
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Information about an AI model available on OpenRouter.
    /// </summary>
    public class Model
    {
        /// <summary>
        /// Unique identifier for the model.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Canonical slug for the model.
        /// </summary>
        [JsonProperty("canonical_slug")]
        public string CanonicalSlug { get; set; } = default!;

        /// <summary>
        /// Hugging Face model identifier, if applicable.
        /// </summary>
        [JsonProperty("hugging_face_id")]
        public string? HuggingFaceId { get; set; } = null;

        /// <summary>
        /// Display name of the model.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Unix timestamp of when the model was created.
        /// </summary>
        [JsonProperty("created")]
        public double Created { get; set; } = default!;

        /// <summary>
        /// Description of the model.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Pricing information for the model.
        /// </summary>
        [JsonProperty("pricing")]
        public PublicPricing Pricing { get; set; } = default!;

        /// <summary>
        /// Maximum context length in tokens.
        /// </summary>
        [JsonProperty("context_length", NullValueHandling = NullValueHandling.Include)]
        public double? ContextLength { get; set; }

        /// <summary>
        /// Model architecture information.
        /// </summary>
        [JsonProperty("architecture")]
        public ModelArchitecture Architecture { get; set; } = default!;

        /// <summary>
        /// Information about the top provider for this model.
        /// </summary>
        [JsonProperty("top_provider")]
        public TopProviderInfo TopProvider { get; set; } = default!;

        /// <summary>
        /// Per-request token limits.
        /// </summary>
        [JsonProperty("per_request_limits", NullValueHandling = NullValueHandling.Include)]
        public PerRequestLimits? PerRequestLimits { get; set; }

        /// <summary>
        /// List of supported parameters for this model.
        /// </summary>
        [JsonProperty("supported_parameters")]
        public List<Parameter> SupportedParameters { get; set; } = default!;

        /// <summary>
        /// Default parameters for this model.
        /// </summary>
        [JsonProperty("default_parameters", NullValueHandling = NullValueHandling.Include)]
        public DefaultParameters? DefaultParameters { get; set; }

        /// <summary>
        /// The date after which the model may be removed. ISO 8601 date string (YYYY-MM-DD) or null if no expiration.
        /// </summary>
        [JsonProperty("expiration_date")]
        public string? ExpirationDate { get; set; } = null;
    }
}