//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7fc732a359c9
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// List of available models.
    /// </summary>
    public class ModelsListResponse
    {
        /// <summary>
        /// List of available models.
        /// </summary>
        [JsonProperty("data")]
        public List<Model> Data { get; set; } = default!;
    }
}