//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 23fb5ff56ee3
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Alternative token with its log probability.
    /// </summary>
    public class OpenResponsesTopLogprobs
    {
        [JsonProperty("token")]
        public string? Token { get; set; }

        [JsonProperty("logprob")]
        public double? Logprob { get; set; }
    }
}