//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 2e45adb1530a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Image generation call completed.
    /// </summary>
    public class OpenResponsesImageGenCallCompleted
    {
        [JsonProperty("type")]
        public OpenResponsesImageGenCallCompletedType Type { get; set; } = default!;

        [JsonProperty("item_id")]
        public string ItemId { get; set; } = default!;

        [JsonProperty("output_index")]
        public double OutputIndex { get; set; } = default!;

        [JsonProperty("sequence_number")]
        public double SequenceNumber { get; set; } = default!;
    }
}