//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 422586f1e07b
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenResponsesWebSearchPreviewToolType
    {
        [JsonProperty("web_search_preview")] WebSearchPreview,
    }

    public static class OpenResponsesWebSearchPreviewToolTypeExtension
    {
        public static string Value(this OpenResponsesWebSearchPreviewToolType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenResponsesWebSearchPreviewToolType ToEnum(this string value)
        {
            foreach (var field in typeof(OpenResponsesWebSearchPreviewToolType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenResponsesWebSearchPreviewToolType)
                    {
                        return (OpenResponsesWebSearchPreviewToolType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenResponsesWebSearchPreviewToolType");
        }
    }
}