//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 52e0ad9ef218
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Web search tool configuration (2025-08-26 version).
    /// </summary>
    public class OpenResponsesWebSearch20250826Tool
    {
        [JsonProperty("type")]
        public OpenResponsesWebSearch20250826ToolType Type { get; set; } = default!;

        [JsonProperty("filters")]
        public OpenResponsesWebSearch20250826ToolFilters? Filters { get; set; } = null;

        /// <summary>
        /// Size of the search context for web search tools.
        /// </summary>
        [JsonProperty("search_context_size")]
        public ResponsesSearchContextSize? SearchContextSize { get; set; }

        /// <summary>
        /// User location information for web search.
        /// </summary>
        [JsonProperty("user_location")]
        public ResponsesWebSearchUserLocation? UserLocation { get; set; } = null;
    }
}