//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0ab5c6600c43
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Image input content item.
    /// </summary>
    public class OpenResponsesEasyInputMessageContentInputImage
    {
        [JsonProperty("type")]
        public OpenResponsesEasyInputMessageContentType Type { get; set; } = default!;

        [JsonProperty("detail")]
        public OpenResponsesEasyInputMessageDetail Detail { get; set; } = default!;

        [JsonProperty("image_url")]
        public string? ImageUrl { get; set; } = null;
    }
}