//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 272718cfabc9
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenAIResponsesInputRoleDeveloper1
    {
        [JsonProperty("developer")] Developer,
    }

    public static class OpenAIResponsesInputRoleDeveloper1Extension
    {
        public static string Value(this OpenAIResponsesInputRoleDeveloper1 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenAIResponsesInputRoleDeveloper1 ToEnum(this string value)
        {
            foreach (var field in typeof(OpenAIResponsesInputRoleDeveloper1).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenAIResponsesInputRoleDeveloper1)
                    {
                        return (OpenAIResponsesInputRoleDeveloper1)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenAIResponsesInputRoleDeveloper1");
        }
    }
}