//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a8b427bba955
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class OpenResponsesEasyInputMessageDetail : IEquatable<OpenResponsesEasyInputMessageDetail>
    {
        public static readonly OpenResponsesEasyInputMessageDetail Auto = new OpenResponsesEasyInputMessageDetail("auto");
        public static readonly OpenResponsesEasyInputMessageDetail High = new OpenResponsesEasyInputMessageDetail("high");
        public static readonly OpenResponsesEasyInputMessageDetail Low = new OpenResponsesEasyInputMessageDetail("low");

        private static readonly Dictionary<string, OpenResponsesEasyInputMessageDetail> _knownValues =
            new Dictionary<string, OpenResponsesEasyInputMessageDetail>() {
                ["auto"] = Auto,
                ["high"] = High,
                ["low"] = Low
            };

        private static readonly ConcurrentDictionary<string, OpenResponsesEasyInputMessageDetail> _values =
            new ConcurrentDictionary<string, OpenResponsesEasyInputMessageDetail>(_knownValues);

        private OpenResponsesEasyInputMessageDetail(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static OpenResponsesEasyInputMessageDetail Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new OpenResponsesEasyInputMessageDetail(value));
        }

        public static implicit operator OpenResponsesEasyInputMessageDetail(string value) => Of(value);
        public static implicit operator string(OpenResponsesEasyInputMessageDetail openresponseseasyinputmessagedetail) => openresponseseasyinputmessagedetail.Value;

        public static OpenResponsesEasyInputMessageDetail[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as OpenResponsesEasyInputMessageDetail);

        public bool Equals(OpenResponsesEasyInputMessageDetail? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}