//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0db33538147a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Event emitted when a response has completed successfully.
    /// </summary>
    public class OpenResponsesStreamEventResponseCompleted
    {
        [JsonProperty("type")]
        public TypeResponseCompleted Type { get; set; } = default!;

        /// <summary>
        /// Complete non-streaming response from the Responses API.
        /// </summary>
        [JsonProperty("response")]
        public OpenResponsesNonStreamingResponse Response { get; set; } = default!;

        [JsonProperty("sequence_number")]
        public double SequenceNumber { get; set; } = default!;
    }
}