//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: b9e4f15120f7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenAIResponsesInputTypeMessage3
    {
        [JsonProperty("message")] Message,
    }

    public static class OpenAIResponsesInputTypeMessage3Extension
    {
        public static string Value(this OpenAIResponsesInputTypeMessage3 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenAIResponsesInputTypeMessage3 ToEnum(this string value)
        {
            foreach (var field in typeof(OpenAIResponsesInputTypeMessage3).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenAIResponsesInputTypeMessage3)
                    {
                        return (OpenAIResponsesInputTypeMessage3)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenAIResponsesInputTypeMessage3");
        }
    }
}