//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 302238b64af1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Event emitted when an error occurs during streaming.
    /// </summary>
    public class OpenResponsesErrorEvent
    {
        [JsonProperty("type")]
        public OpenResponsesErrorEventType Type { get; set; } = default!;

        [JsonProperty("code", NullValueHandling = NullValueHandling.Include)]
        public string? Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        [JsonProperty("param", NullValueHandling = NullValueHandling.Include)]
        public string? Param { get; set; }

        [JsonProperty("sequence_number")]
        public double SequenceNumber { get; set; } = default!;
    }
}