//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 043d31946b75
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class OpenAIResponsesInputContent1Type
    {
        private OpenAIResponsesInputContent1Type(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static OpenAIResponsesInputContent1Type InputText
        {
            get {
                return new OpenAIResponsesInputContent1Type("input_text");
            }
        }

        public static OpenAIResponsesInputContent1Type InputImage
        {
            get {
                return new OpenAIResponsesInputContent1Type("input_image");
            }
        }

        public static OpenAIResponsesInputContent1Type InputFile
        {
            get {
                return new OpenAIResponsesInputContent1Type("input_file");
            }
        }

        public static OpenAIResponsesInputContent1Type InputAudio
        {
            get {
                return new OpenAIResponsesInputContent1Type("input_audio");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(OpenAIResponsesInputContent1Type v)
        {
            return v.Value;
        }
        public static OpenAIResponsesInputContent1Type FromString(string v)
        {
            switch (v)
            {
                case "input_text":
                    return InputText;
                case "input_image":
                    return InputImage;
                case "input_file":
                    return InputFile;
                case "input_audio":
                    return InputAudio;
                default:
                    throw new ArgumentException("Invalid value for OpenAIResponsesInputContent1Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OpenAIResponsesInputContent1Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(OpenAIResponsesInputContent1.OpenAIResponsesInputContent1Converter))]
    public class OpenAIResponsesInputContent1
    {
        public OpenAIResponsesInputContent1(OpenAIResponsesInputContent1Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseInputText? ResponseInputText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseInputImage? ResponseInputImage { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseInputFile? ResponseInputFile { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseInputAudio? ResponseInputAudio { get; set; }

        public OpenAIResponsesInputContent1Type Type { get; set; }

        public static OpenAIResponsesInputContent1 CreateInputText(ResponseInputText inputText)
        {
            OpenAIResponsesInputContent1Type typ = OpenAIResponsesInputContent1Type.InputText;
            string typStr = OpenAIResponsesInputContent1Type.InputText.ToString();
            inputText.Type = ResponseInputTextTypeExtension.ToEnum(OpenAIResponsesInputContent1Type.InputText.ToString());
            OpenAIResponsesInputContent1 res = new OpenAIResponsesInputContent1(typ);
            res.ResponseInputText = inputText;
            return res;
        }

        public static OpenAIResponsesInputContent1 CreateInputImage(ResponseInputImage inputImage)
        {
            OpenAIResponsesInputContent1Type typ = OpenAIResponsesInputContent1Type.InputImage;
            string typStr = OpenAIResponsesInputContent1Type.InputImage.ToString();
            inputImage.Type = ResponseInputImageTypeExtension.ToEnum(OpenAIResponsesInputContent1Type.InputImage.ToString());
            OpenAIResponsesInputContent1 res = new OpenAIResponsesInputContent1(typ);
            res.ResponseInputImage = inputImage;
            return res;
        }

        public static OpenAIResponsesInputContent1 CreateInputFile(ResponseInputFile inputFile)
        {
            OpenAIResponsesInputContent1Type typ = OpenAIResponsesInputContent1Type.InputFile;
            string typStr = OpenAIResponsesInputContent1Type.InputFile.ToString();
            inputFile.Type = ResponseInputFileTypeExtension.ToEnum(OpenAIResponsesInputContent1Type.InputFile.ToString());
            OpenAIResponsesInputContent1 res = new OpenAIResponsesInputContent1(typ);
            res.ResponseInputFile = inputFile;
            return res;
        }

        public static OpenAIResponsesInputContent1 CreateInputAudio(ResponseInputAudio inputAudio)
        {
            OpenAIResponsesInputContent1Type typ = OpenAIResponsesInputContent1Type.InputAudio;
            string typStr = OpenAIResponsesInputContent1Type.InputAudio.ToString();
            inputAudio.Type = ResponseInputAudioTypeExtension.ToEnum(OpenAIResponsesInputContent1Type.InputAudio.ToString());
            OpenAIResponsesInputContent1 res = new OpenAIResponsesInputContent1(typ);
            res.ResponseInputAudio = inputAudio;
            return res;
        }

        public class OpenAIResponsesInputContent1Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(OpenAIResponsesInputContent1);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == OpenAIResponsesInputContent1Type.InputText.ToString())
                {
                    ResponseInputText responseInputText = ResponseBodyDeserializer.DeserializeNotNull<ResponseInputText>(jo.ToString());
                    return CreateInputText(responseInputText);
                }
                if (discriminator == OpenAIResponsesInputContent1Type.InputImage.ToString())
                {
                    ResponseInputImage responseInputImage = ResponseBodyDeserializer.DeserializeNotNull<ResponseInputImage>(jo.ToString());
                    return CreateInputImage(responseInputImage);
                }
                if (discriminator == OpenAIResponsesInputContent1Type.InputFile.ToString())
                {
                    ResponseInputFile responseInputFile = ResponseBodyDeserializer.DeserializeNotNull<ResponseInputFile>(jo.ToString());
                    return CreateInputFile(responseInputFile);
                }
                if (discriminator == OpenAIResponsesInputContent1Type.InputAudio.ToString())
                {
                    ResponseInputAudio responseInputAudio = ResponseBodyDeserializer.DeserializeNotNull<ResponseInputAudio>(jo.ToString());
                    return CreateInputAudio(responseInputAudio);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                OpenAIResponsesInputContent1 res = (OpenAIResponsesInputContent1)value;

                if (res.ResponseInputText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseInputText));
                    return;
                }

                if (res.ResponseInputImage != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseInputImage));
                    return;
                }

                if (res.ResponseInputFile != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseInputFile));
                    return;
                }

                if (res.ResponseInputAudio != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseInputAudio));
                    return;
                }
            }
        }
    }
}