//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: d9202acb2a8a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class OpenAIResponsesInputUnion2Type
    {
        private OpenAIResponsesInputUnion2Type(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static OpenAIResponsesInputUnion2Type OpenAIResponsesInputMessage3
        {
            get {
                return new OpenAIResponsesInputUnion2Type("OpenAIResponsesInput_Message_3");
            }
        }

        public static OpenAIResponsesInputUnion2Type OpenAIResponsesInputMessage4
        {
            get {
                return new OpenAIResponsesInputUnion2Type("OpenAIResponsesInput_Message_4");
            }
        }

        public static OpenAIResponsesInputUnion2Type OpenAIResponsesInputFunctionCallOutput2
        {
            get {
                return new OpenAIResponsesInputUnion2Type("OpenAIResponsesInput_FunctionCallOutput_2");
            }
        }

        public static OpenAIResponsesInputUnion2Type OpenAIResponsesInputFunctionCall2
        {
            get {
                return new OpenAIResponsesInputUnion2Type("OpenAIResponsesInput_FunctionCall_2");
            }
        }

        public static OpenAIResponsesInputUnion2Type OutputItemImageGenerationCall
        {
            get {
                return new OpenAIResponsesInputUnion2Type("OutputItemImageGenerationCall");
            }
        }

        public static OpenAIResponsesInputUnion2Type OutputMessage
        {
            get {
                return new OpenAIResponsesInputUnion2Type("OutputMessage");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(OpenAIResponsesInputUnion2Type v)
        {
            return v.Value;
        }
        public static OpenAIResponsesInputUnion2Type FromString(string v)
        {
            switch (v)
            {
                case "OpenAIResponsesInput_Message_3":
                    return OpenAIResponsesInputMessage3;
                case "OpenAIResponsesInput_Message_4":
                    return OpenAIResponsesInputMessage4;
                case "OpenAIResponsesInput_FunctionCallOutput_2":
                    return OpenAIResponsesInputFunctionCallOutput2;
                case "OpenAIResponsesInput_FunctionCall_2":
                    return OpenAIResponsesInputFunctionCall2;
                case "OutputItemImageGenerationCall":
                    return OutputItemImageGenerationCall;
                case "OutputMessage":
                    return OutputMessage;
                default:
                    throw new ArgumentException("Invalid value for OpenAIResponsesInputUnion2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OpenAIResponsesInputUnion2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(OpenAIResponsesInputUnion2.OpenAIResponsesInputUnion2Converter))]
    public class OpenAIResponsesInputUnion2
    {
        public OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenAIResponsesInputMessage3? OpenAIResponsesInputMessage3 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenAIResponsesInputMessage4? OpenAIResponsesInputMessage4 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenAIResponsesInputFunctionCallOutput2? OpenAIResponsesInputFunctionCallOutput2 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenAIResponsesInputFunctionCall2? OpenAIResponsesInputFunctionCall2 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OutputItemImageGenerationCall? OutputItemImageGenerationCall { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OutputMessage? OutputMessage { get; set; }

        public OpenAIResponsesInputUnion2Type Type { get; set; }
        public static OpenAIResponsesInputUnion2 CreateOpenAIResponsesInputMessage3(OpenAIResponsesInputMessage3 openAIResponsesInputMessage3)
        {
            OpenAIResponsesInputUnion2Type typ = OpenAIResponsesInputUnion2Type.OpenAIResponsesInputMessage3;

            OpenAIResponsesInputUnion2 res = new OpenAIResponsesInputUnion2(typ);
            res.OpenAIResponsesInputMessage3 = openAIResponsesInputMessage3;
            return res;
        }
        public static OpenAIResponsesInputUnion2 CreateOpenAIResponsesInputMessage4(OpenAIResponsesInputMessage4 openAIResponsesInputMessage4)
        {
            OpenAIResponsesInputUnion2Type typ = OpenAIResponsesInputUnion2Type.OpenAIResponsesInputMessage4;

            OpenAIResponsesInputUnion2 res = new OpenAIResponsesInputUnion2(typ);
            res.OpenAIResponsesInputMessage4 = openAIResponsesInputMessage4;
            return res;
        }
        public static OpenAIResponsesInputUnion2 CreateOpenAIResponsesInputFunctionCallOutput2(OpenAIResponsesInputFunctionCallOutput2 openAIResponsesInputFunctionCallOutput2)
        {
            OpenAIResponsesInputUnion2Type typ = OpenAIResponsesInputUnion2Type.OpenAIResponsesInputFunctionCallOutput2;

            OpenAIResponsesInputUnion2 res = new OpenAIResponsesInputUnion2(typ);
            res.OpenAIResponsesInputFunctionCallOutput2 = openAIResponsesInputFunctionCallOutput2;
            return res;
        }
        public static OpenAIResponsesInputUnion2 CreateOpenAIResponsesInputFunctionCall2(OpenAIResponsesInputFunctionCall2 openAIResponsesInputFunctionCall2)
        {
            OpenAIResponsesInputUnion2Type typ = OpenAIResponsesInputUnion2Type.OpenAIResponsesInputFunctionCall2;

            OpenAIResponsesInputUnion2 res = new OpenAIResponsesInputUnion2(typ);
            res.OpenAIResponsesInputFunctionCall2 = openAIResponsesInputFunctionCall2;
            return res;
        }
        public static OpenAIResponsesInputUnion2 CreateOutputItemImageGenerationCall(OutputItemImageGenerationCall outputItemImageGenerationCall)
        {
            OpenAIResponsesInputUnion2Type typ = OpenAIResponsesInputUnion2Type.OutputItemImageGenerationCall;

            OpenAIResponsesInputUnion2 res = new OpenAIResponsesInputUnion2(typ);
            res.OutputItemImageGenerationCall = outputItemImageGenerationCall;
            return res;
        }
        public static OpenAIResponsesInputUnion2 CreateOutputMessage(OutputMessage outputMessage)
        {
            OpenAIResponsesInputUnion2Type typ = OpenAIResponsesInputUnion2Type.OutputMessage;

            OpenAIResponsesInputUnion2 res = new OpenAIResponsesInputUnion2(typ);
            res.OutputMessage = outputMessage;
            return res;
        }

        public class OpenAIResponsesInputUnion2Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(OpenAIResponsesInputUnion2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputMessage3) {
                        OpenAIResponsesInputMessage3 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenAIResponsesInputMessage3>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenAIResponsesInputMessage3), new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputMessage3), "OpenAIResponsesInputMessage3"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputMessage4) {
                        OpenAIResponsesInputMessage4 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenAIResponsesInputMessage4>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenAIResponsesInputMessage4), new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputMessage4), "OpenAIResponsesInputMessage4"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OutputItemImageGenerationCall) {
                        OutputItemImageGenerationCall = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OutputItemImageGenerationCall>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OutputItemImageGenerationCall), new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OutputItemImageGenerationCall), "OutputItemImageGenerationCall"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputFunctionCallOutput2) {
                        OpenAIResponsesInputFunctionCallOutput2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenAIResponsesInputFunctionCallOutput2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenAIResponsesInputFunctionCallOutput2), new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputFunctionCallOutput2), "OpenAIResponsesInputFunctionCallOutput2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OutputMessage) {
                        OutputMessage = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OutputMessage>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OutputMessage), new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OutputMessage), "OutputMessage"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputFunctionCall2) {
                        OpenAIResponsesInputFunctionCall2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenAIResponsesInputFunctionCall2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenAIResponsesInputFunctionCall2), new OpenAIResponsesInputUnion2(OpenAIResponsesInputUnion2Type.OpenAIResponsesInputFunctionCall2), "OpenAIResponsesInputFunctionCall2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                OpenAIResponsesInputUnion2 res = (OpenAIResponsesInputUnion2)value;

                if (res.OpenAIResponsesInputMessage3 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenAIResponsesInputMessage3));
                    return;
                }

                if (res.OpenAIResponsesInputMessage4 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenAIResponsesInputMessage4));
                    return;
                }

                if (res.OpenAIResponsesInputFunctionCallOutput2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenAIResponsesInputFunctionCallOutput2));
                    return;
                }

                if (res.OpenAIResponsesInputFunctionCall2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenAIResponsesInputFunctionCall2));
                    return;
                }

                if (res.OutputItemImageGenerationCall != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OutputItemImageGenerationCall));
                    return;
                }

                if (res.OutputMessage != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OutputMessage));
                    return;
                }
            }
        }
    }
}