//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 3cb927212c6f
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// Log probability information for a token.
    /// </summary>
    public class OpenResponsesLogProbs
    {
        [JsonProperty("logprob")]
        public double Logprob { get; set; } = default!;

        [JsonProperty("token")]
        public string Token { get; set; } = default!;

        [JsonProperty("top_logprobs")]
        public List<OpenResponsesTopLogprobs>? TopLogprobs { get; set; }
    }
}