//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ba351a61977b
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class OpenResponsesInputMessageItemRoleUnionType
    {
        private OpenResponsesInputMessageItemRoleUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static OpenResponsesInputMessageItemRoleUnionType OpenResponsesInputMessageItemRoleUser
        {
            get {
                return new OpenResponsesInputMessageItemRoleUnionType("OpenResponsesInputMessageItem_role_User");
            }
        }

        public static OpenResponsesInputMessageItemRoleUnionType OpenResponsesInputMessageItemRoleSystem
        {
            get {
                return new OpenResponsesInputMessageItemRoleUnionType("OpenResponsesInputMessageItem_role_System");
            }
        }

        public static OpenResponsesInputMessageItemRoleUnionType OpenResponsesInputMessageItemRoleDeveloper
        {
            get {
                return new OpenResponsesInputMessageItemRoleUnionType("OpenResponsesInputMessageItem_role_Developer");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(OpenResponsesInputMessageItemRoleUnionType v)
        {
            return v.Value;
        }
        public static OpenResponsesInputMessageItemRoleUnionType FromString(string v)
        {
            switch (v)
            {
                case "OpenResponsesInputMessageItem_role_User":
                    return OpenResponsesInputMessageItemRoleUser;
                case "OpenResponsesInputMessageItem_role_System":
                    return OpenResponsesInputMessageItemRoleSystem;
                case "OpenResponsesInputMessageItem_role_Developer":
                    return OpenResponsesInputMessageItemRoleDeveloper;
                default:
                    throw new ArgumentException("Invalid value for OpenResponsesInputMessageItemRoleUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OpenResponsesInputMessageItemRoleUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(OpenResponsesInputMessageItemRoleUnion.OpenResponsesInputMessageItemRoleUnionConverter))]
    public class OpenResponsesInputMessageItemRoleUnion
    {
        public OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesInputMessageItemRoleUser? OpenResponsesInputMessageItemRoleUser { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesInputMessageItemRoleSystem? OpenResponsesInputMessageItemRoleSystem { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesInputMessageItemRoleDeveloper? OpenResponsesInputMessageItemRoleDeveloper { get; set; }

        public OpenResponsesInputMessageItemRoleUnionType Type { get; set; }
        public static OpenResponsesInputMessageItemRoleUnion CreateOpenResponsesInputMessageItemRoleUser(OpenResponsesInputMessageItemRoleUser openResponsesInputMessageItemRoleUser)
        {
            OpenResponsesInputMessageItemRoleUnionType typ = OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleUser;

            OpenResponsesInputMessageItemRoleUnion res = new OpenResponsesInputMessageItemRoleUnion(typ);
            res.OpenResponsesInputMessageItemRoleUser = openResponsesInputMessageItemRoleUser;
            return res;
        }
        public static OpenResponsesInputMessageItemRoleUnion CreateOpenResponsesInputMessageItemRoleSystem(OpenResponsesInputMessageItemRoleSystem openResponsesInputMessageItemRoleSystem)
        {
            OpenResponsesInputMessageItemRoleUnionType typ = OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleSystem;

            OpenResponsesInputMessageItemRoleUnion res = new OpenResponsesInputMessageItemRoleUnion(typ);
            res.OpenResponsesInputMessageItemRoleSystem = openResponsesInputMessageItemRoleSystem;
            return res;
        }
        public static OpenResponsesInputMessageItemRoleUnion CreateOpenResponsesInputMessageItemRoleDeveloper(OpenResponsesInputMessageItemRoleDeveloper openResponsesInputMessageItemRoleDeveloper)
        {
            OpenResponsesInputMessageItemRoleUnionType typ = OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleDeveloper;

            OpenResponsesInputMessageItemRoleUnion res = new OpenResponsesInputMessageItemRoleUnion(typ);
            res.OpenResponsesInputMessageItemRoleDeveloper = openResponsesInputMessageItemRoleDeveloper;
            return res;
        }

        public class OpenResponsesInputMessageItemRoleUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(OpenResponsesInputMessageItemRoleUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleUser) {
                        OpenResponsesInputMessageItemRoleUser = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenResponsesInputMessageItemRoleUser>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenResponsesInputMessageItemRoleUser), new OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleUser), "OpenResponsesInputMessageItemRoleUser"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleSystem) {
                        OpenResponsesInputMessageItemRoleSystem = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenResponsesInputMessageItemRoleSystem>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenResponsesInputMessageItemRoleSystem), new OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleSystem), "OpenResponsesInputMessageItemRoleSystem"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleDeveloper) {
                        OpenResponsesInputMessageItemRoleDeveloper = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<OpenResponsesInputMessageItemRoleDeveloper>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(OpenResponsesInputMessageItemRoleDeveloper), new OpenResponsesInputMessageItemRoleUnion(OpenResponsesInputMessageItemRoleUnionType.OpenResponsesInputMessageItemRoleDeveloper), "OpenResponsesInputMessageItemRoleDeveloper"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                OpenResponsesInputMessageItemRoleUnion res = (OpenResponsesInputMessageItemRoleUnion)value;

                if (res.OpenResponsesInputMessageItemRoleUser != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesInputMessageItemRoleUser));
                    return;
                }

                if (res.OpenResponsesInputMessageItemRoleSystem != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesInputMessageItemRoleSystem));
                    return;
                }

                if (res.OpenResponsesInputMessageItemRoleDeveloper != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesInputMessageItemRoleDeveloper));
                    return;
                }
            }
        }
    }
}