//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 37a68c3e03d1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class OpenAIResponsesServiceTier : IEquatable<OpenAIResponsesServiceTier>
    {
        public static readonly OpenAIResponsesServiceTier Auto = new OpenAIResponsesServiceTier("auto");
        public static readonly OpenAIResponsesServiceTier Default = new OpenAIResponsesServiceTier("default");
        public static readonly OpenAIResponsesServiceTier Flex = new OpenAIResponsesServiceTier("flex");
        public static readonly OpenAIResponsesServiceTier Priority = new OpenAIResponsesServiceTier("priority");
        public static readonly OpenAIResponsesServiceTier Scale = new OpenAIResponsesServiceTier("scale");

        private static readonly Dictionary<string, OpenAIResponsesServiceTier> _knownValues =
            new Dictionary<string, OpenAIResponsesServiceTier>() {
                ["auto"] = Auto,
                ["default"] = Default,
                ["flex"] = Flex,
                ["priority"] = Priority,
                ["scale"] = Scale
            };

        private static readonly ConcurrentDictionary<string, OpenAIResponsesServiceTier> _values =
            new ConcurrentDictionary<string, OpenAIResponsesServiceTier>(_knownValues);

        private OpenAIResponsesServiceTier(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static OpenAIResponsesServiceTier Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new OpenAIResponsesServiceTier(value));
        }

        public static implicit operator OpenAIResponsesServiceTier(string value) => Of(value);
        public static implicit operator string(OpenAIResponsesServiceTier openairesponsesservicetier) => openairesponsesservicetier.Value;

        public static OpenAIResponsesServiceTier[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as OpenAIResponsesServiceTier);

        public bool Equals(OpenAIResponsesServiceTier? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}