//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 5e94814ae589
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class OpenResponsesRequestToolUnionType
    {
        private OpenResponsesRequestToolUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static OpenResponsesRequestToolUnionType Function
        {
            get {
                return new OpenResponsesRequestToolUnionType("function");
            }
        }

        public static OpenResponsesRequestToolUnionType WebSearchPreview
        {
            get {
                return new OpenResponsesRequestToolUnionType("web_search_preview");
            }
        }

        public static OpenResponsesRequestToolUnionType WebSearchPreview20250311
        {
            get {
                return new OpenResponsesRequestToolUnionType("web_search_preview_2025_03_11");
            }
        }

        public static OpenResponsesRequestToolUnionType WebSearch
        {
            get {
                return new OpenResponsesRequestToolUnionType("web_search");
            }
        }

        public static OpenResponsesRequestToolUnionType WebSearch20250826
        {
            get {
                return new OpenResponsesRequestToolUnionType("web_search_2025_08_26");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(OpenResponsesRequestToolUnionType v)
        {
            return v.Value;
        }
        public static OpenResponsesRequestToolUnionType FromString(string v)
        {
            switch (v)
            {
                case "function":
                    return Function;
                case "web_search_preview":
                    return WebSearchPreview;
                case "web_search_preview_2025_03_11":
                    return WebSearchPreview20250311;
                case "web_search":
                    return WebSearch;
                case "web_search_2025_08_26":
                    return WebSearch20250826;
                default:
                    throw new ArgumentException("Invalid value for OpenResponsesRequestToolUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OpenResponsesRequestToolUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(OpenResponsesRequestToolUnion.OpenResponsesRequestToolUnionConverter))]
    public class OpenResponsesRequestToolUnion
    {
        public OpenResponsesRequestToolUnion(OpenResponsesRequestToolUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesRequestToolFunction? OpenResponsesRequestToolFunction { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesWebSearchPreviewTool? OpenResponsesWebSearchPreviewTool { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesWebSearchPreview20250311Tool? OpenResponsesWebSearchPreview20250311Tool { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesWebSearchTool? OpenResponsesWebSearchTool { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenResponsesWebSearch20250826Tool? OpenResponsesWebSearch20250826Tool { get; set; }

        public OpenResponsesRequestToolUnionType Type { get; set; }

        public static OpenResponsesRequestToolUnion CreateFunction(OpenResponsesRequestToolFunction function)
        {
            OpenResponsesRequestToolUnionType typ = OpenResponsesRequestToolUnionType.Function;
            string typStr = OpenResponsesRequestToolUnionType.Function.ToString();
            function.Type = OpenResponsesRequestTypeExtension.ToEnum(OpenResponsesRequestToolUnionType.Function.ToString());
            OpenResponsesRequestToolUnion res = new OpenResponsesRequestToolUnion(typ);
            res.OpenResponsesRequestToolFunction = function;
            return res;
        }

        public static OpenResponsesRequestToolUnion CreateWebSearchPreview(OpenResponsesWebSearchPreviewTool webSearchPreview)
        {
            OpenResponsesRequestToolUnionType typ = OpenResponsesRequestToolUnionType.WebSearchPreview;
            string typStr = OpenResponsesRequestToolUnionType.WebSearchPreview.ToString();
            webSearchPreview.Type = OpenResponsesWebSearchPreviewToolTypeExtension.ToEnum(OpenResponsesRequestToolUnionType.WebSearchPreview.ToString());
            OpenResponsesRequestToolUnion res = new OpenResponsesRequestToolUnion(typ);
            res.OpenResponsesWebSearchPreviewTool = webSearchPreview;
            return res;
        }

        public static OpenResponsesRequestToolUnion CreateWebSearchPreview20250311(OpenResponsesWebSearchPreview20250311Tool webSearchPreview20250311)
        {
            OpenResponsesRequestToolUnionType typ = OpenResponsesRequestToolUnionType.WebSearchPreview20250311;
            string typStr = OpenResponsesRequestToolUnionType.WebSearchPreview20250311.ToString();
            webSearchPreview20250311.Type = OpenResponsesWebSearchPreview20250311ToolTypeExtension.ToEnum(OpenResponsesRequestToolUnionType.WebSearchPreview20250311.ToString());
            OpenResponsesRequestToolUnion res = new OpenResponsesRequestToolUnion(typ);
            res.OpenResponsesWebSearchPreview20250311Tool = webSearchPreview20250311;
            return res;
        }

        public static OpenResponsesRequestToolUnion CreateWebSearch(OpenResponsesWebSearchTool webSearch)
        {
            OpenResponsesRequestToolUnionType typ = OpenResponsesRequestToolUnionType.WebSearch;
            string typStr = OpenResponsesRequestToolUnionType.WebSearch.ToString();
            webSearch.Type = OpenResponsesWebSearchToolTypeExtension.ToEnum(OpenResponsesRequestToolUnionType.WebSearch.ToString());
            OpenResponsesRequestToolUnion res = new OpenResponsesRequestToolUnion(typ);
            res.OpenResponsesWebSearchTool = webSearch;
            return res;
        }

        public static OpenResponsesRequestToolUnion CreateWebSearch20250826(OpenResponsesWebSearch20250826Tool webSearch20250826)
        {
            OpenResponsesRequestToolUnionType typ = OpenResponsesRequestToolUnionType.WebSearch20250826;
            string typStr = OpenResponsesRequestToolUnionType.WebSearch20250826.ToString();
            webSearch20250826.Type = OpenResponsesWebSearch20250826ToolTypeExtension.ToEnum(OpenResponsesRequestToolUnionType.WebSearch20250826.ToString());
            OpenResponsesRequestToolUnion res = new OpenResponsesRequestToolUnion(typ);
            res.OpenResponsesWebSearch20250826Tool = webSearch20250826;
            return res;
        }

        public class OpenResponsesRequestToolUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(OpenResponsesRequestToolUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == OpenResponsesRequestToolUnionType.Function.ToString())
                {
                    OpenResponsesRequestToolFunction openResponsesRequestToolFunction = ResponseBodyDeserializer.DeserializeNotNull<OpenResponsesRequestToolFunction>(jo.ToString());
                    return CreateFunction(openResponsesRequestToolFunction);
                }
                if (discriminator == OpenResponsesRequestToolUnionType.WebSearchPreview.ToString())
                {
                    OpenResponsesWebSearchPreviewTool openResponsesWebSearchPreviewTool = ResponseBodyDeserializer.DeserializeNotNull<OpenResponsesWebSearchPreviewTool>(jo.ToString());
                    return CreateWebSearchPreview(openResponsesWebSearchPreviewTool);
                }
                if (discriminator == OpenResponsesRequestToolUnionType.WebSearchPreview20250311.ToString())
                {
                    OpenResponsesWebSearchPreview20250311Tool openResponsesWebSearchPreview20250311Tool = ResponseBodyDeserializer.DeserializeNotNull<OpenResponsesWebSearchPreview20250311Tool>(jo.ToString());
                    return CreateWebSearchPreview20250311(openResponsesWebSearchPreview20250311Tool);
                }
                if (discriminator == OpenResponsesRequestToolUnionType.WebSearch.ToString())
                {
                    OpenResponsesWebSearchTool openResponsesWebSearchTool = ResponseBodyDeserializer.DeserializeNotNull<OpenResponsesWebSearchTool>(jo.ToString());
                    return CreateWebSearch(openResponsesWebSearchTool);
                }
                if (discriminator == OpenResponsesRequestToolUnionType.WebSearch20250826.ToString())
                {
                    OpenResponsesWebSearch20250826Tool openResponsesWebSearch20250826Tool = ResponseBodyDeserializer.DeserializeNotNull<OpenResponsesWebSearch20250826Tool>(jo.ToString());
                    return CreateWebSearch20250826(openResponsesWebSearch20250826Tool);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                OpenResponsesRequestToolUnion res = (OpenResponsesRequestToolUnion)value;

                if (res.OpenResponsesRequestToolFunction != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesRequestToolFunction));
                    return;
                }

                if (res.OpenResponsesWebSearchPreviewTool != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesWebSearchPreviewTool));
                    return;
                }

                if (res.OpenResponsesWebSearchPreview20250311Tool != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesWebSearchPreview20250311Tool));
                    return;
                }

                if (res.OpenResponsesWebSearchTool != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesWebSearchTool));
                    return;
                }

                if (res.OpenResponsesWebSearch20250826Tool != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenResponsesWebSearch20250826Tool));
                    return;
                }
            }
        }
    }
}