//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 32b80912162e
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// Function tool definition.
    /// </summary>
    public class OpenResponsesRequestToolFunction
    {
        [JsonProperty("type")]
        public OpenResponsesRequestType Type { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        [JsonProperty("strict")]
        public bool? Strict { get; set; } = null;

        [JsonProperty("parameters", NullValueHandling = NullValueHandling.Include)]
        public Dictionary<string, object?>? Parameters { get; set; }
    }
}