//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 8858dff504aa
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenResponsesWebSearch20250826ToolType
    {
        [JsonProperty("web_search_2025_08_26")] WebSearch20250826,
    }

    public static class OpenResponsesWebSearch20250826ToolTypeExtension
    {
        public static string Value(this OpenResponsesWebSearch20250826ToolType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenResponsesWebSearch20250826ToolType ToEnum(this string value)
        {
            foreach (var field in typeof(OpenResponsesWebSearch20250826ToolType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenResponsesWebSearch20250826ToolType)
                    {
                        return (OpenResponsesWebSearch20250826ToolType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenResponsesWebSearch20250826ToolType");
        }
    }
}