//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7347b5785dbe
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class OpenAIResponsesReasoningEffort : IEquatable<OpenAIResponsesReasoningEffort>
    {
        public static readonly OpenAIResponsesReasoningEffort Xhigh = new OpenAIResponsesReasoningEffort("xhigh");
        public static readonly OpenAIResponsesReasoningEffort High = new OpenAIResponsesReasoningEffort("high");
        public static readonly OpenAIResponsesReasoningEffort Medium = new OpenAIResponsesReasoningEffort("medium");
        public static readonly OpenAIResponsesReasoningEffort Low = new OpenAIResponsesReasoningEffort("low");
        public static readonly OpenAIResponsesReasoningEffort Minimal = new OpenAIResponsesReasoningEffort("minimal");
        public static readonly OpenAIResponsesReasoningEffort None = new OpenAIResponsesReasoningEffort("none");

        private static readonly Dictionary<string, OpenAIResponsesReasoningEffort> _knownValues =
            new Dictionary<string, OpenAIResponsesReasoningEffort>() {
                ["xhigh"] = Xhigh,
                ["high"] = High,
                ["medium"] = Medium,
                ["low"] = Low,
                ["minimal"] = Minimal,
                ["none"] = None
            };

        private static readonly ConcurrentDictionary<string, OpenAIResponsesReasoningEffort> _values =
            new ConcurrentDictionary<string, OpenAIResponsesReasoningEffort>(_knownValues);

        private OpenAIResponsesReasoningEffort(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static OpenAIResponsesReasoningEffort Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new OpenAIResponsesReasoningEffort(value));
        }

        public static implicit operator OpenAIResponsesReasoningEffort(string value) => Of(value);
        public static implicit operator string(OpenAIResponsesReasoningEffort openairesponsesreasoningeffort) => openairesponsesreasoningeffort.Value;

        public static OpenAIResponsesReasoningEffort[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as OpenAIResponsesReasoningEffort);

        public bool Equals(OpenAIResponsesReasoningEffort? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}