//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: f91ec5560071
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenAIResponsesInputRoleEnum2
    {
        [JsonProperty("user")] User,
        [JsonProperty("system")] System,
        [JsonProperty("developer")] Developer,
    }

    public static class OpenAIResponsesInputRoleEnum2Extension
    {
        public static string Value(this OpenAIResponsesInputRoleEnum2 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenAIResponsesInputRoleEnum2 ToEnum(this string value)
        {
            foreach (var field in typeof(OpenAIResponsesInputRoleEnum2).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenAIResponsesInputRoleEnum2)
                    {
                        return (OpenAIResponsesInputRoleEnum2)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenAIResponsesInputRoleEnum2");
        }
    }
}