//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: bfc8774bac5a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenAIResponsesInputTypeFunctionCallOutput2
    {
        [JsonProperty("function_call_output")] FunctionCallOutput,
    }

    public static class OpenAIResponsesInputTypeFunctionCallOutput2Extension
    {
        public static string Value(this OpenAIResponsesInputTypeFunctionCallOutput2 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenAIResponsesInputTypeFunctionCallOutput2 ToEnum(this string value)
        {
            foreach (var field in typeof(OpenAIResponsesInputTypeFunctionCallOutput2).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenAIResponsesInputTypeFunctionCallOutput2)
                    {
                        return (OpenAIResponsesInputTypeFunctionCallOutput2)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenAIResponsesInputTypeFunctionCallOutput2");
        }
    }
}