//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: b28444daf7a4
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenResponsesWebSearchPreview20250311ToolType
    {
        [JsonProperty("web_search_preview_2025_03_11")] WebSearchPreview20250311,
    }

    public static class OpenResponsesWebSearchPreview20250311ToolTypeExtension
    {
        public static string Value(this OpenResponsesWebSearchPreview20250311ToolType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenResponsesWebSearchPreview20250311ToolType ToEnum(this string value)
        {
            foreach (var field in typeof(OpenResponsesWebSearchPreview20250311ToolType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenResponsesWebSearchPreview20250311ToolType)
                    {
                        return (OpenResponsesWebSearchPreview20250311ToolType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenResponsesWebSearchPreview20250311ToolType");
        }
    }
}