//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 45b966ab94a3
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class OpenAIResponsesInputFunctionCall2
    {
        [JsonProperty("type")]
        public OpenAIResponsesInputTypeFunctionCall2 Type { get; set; } = default!;

        [JsonProperty("call_id")]
        public string CallId { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("arguments")]
        public string Arguments { get; set; } = default!;

        [JsonProperty("id")]
        public string? Id { get; set; }

        [JsonProperty("status")]
        public ToolCallStatus? Status { get; set; } = null;
    }
}