//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: c12d1808ca7d
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum OpenAIResponsesInputRoleUser1
    {
        [JsonProperty("user")] User,
    }

    public static class OpenAIResponsesInputRoleUser1Extension
    {
        public static string Value(this OpenAIResponsesInputRoleUser1 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OpenAIResponsesInputRoleUser1 ToEnum(this string value)
        {
            foreach (var field in typeof(OpenAIResponsesInputRoleUser1).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OpenAIResponsesInputRoleUser1)
                    {
                        return (OpenAIResponsesInputRoleUser1)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OpenAIResponsesInputRoleUser1");
        }
    }
}