//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 8ab2d8be43b3
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Event emitted when a text annotation is added to output.
    /// </summary>
    public class OpenResponsesStreamEventResponseOutputTextAnnotationAdded
    {
        [JsonProperty("type")]
        public TypeResponseOutputTextAnnotationAdded Type { get; set; } = default!;

        [JsonProperty("output_index")]
        public double OutputIndex { get; set; } = default!;

        [JsonProperty("item_id")]
        public string ItemId { get; set; } = default!;

        [JsonProperty("content_index")]
        public double ContentIndex { get; set; } = default!;

        [JsonProperty("sequence_number")]
        public double SequenceNumber { get; set; } = default!;

        [JsonProperty("annotation_index")]
        public double AnnotationIndex { get; set; } = default!;

        [JsonProperty("annotation", NullValueHandling = NullValueHandling.Include)]
        public OpenAIResponsesAnnotation Annotation { get; set; } = default!;

        public FileCitation? GetAnnotationFileCitation()
        {
            return Annotation.FileCitation;
        }

        public URLCitation? GetAnnotationUrlCitation()
        {
            return Annotation.URLCitation;
        }

        public FilePath? GetAnnotationFilePath()
        {
            return Annotation.FilePath;
        }
    }
}