//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: d7f2a4f56805
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Event emitted when a content part is complete.
    /// </summary>
    public class OpenResponsesStreamEventResponseContentPartDone
    {
        [JsonProperty("type")]
        public TypeResponseContentPartDone Type { get; set; } = default!;

        [JsonProperty("output_index")]
        public double OutputIndex { get; set; } = default!;

        [JsonProperty("item_id")]
        public string ItemId { get; set; } = default!;

        [JsonProperty("content_index")]
        public double ContentIndex { get; set; } = default!;

        [JsonProperty("part", NullValueHandling = NullValueHandling.Include)]
        public Part2 Part { get; set; } = default!;

        public ResponseOutputText? GetPartOutputText()
        {
            return Part.ResponseOutputText;
        }

        public ReasoningTextContent? GetPartReasoningText()
        {
            return Part.ReasoningTextContent;
        }

        public OpenAIResponsesRefusalContent? GetPartRefusal()
        {
            return Part.OpenAIResponsesRefusalContent;
        }

        [JsonProperty("sequence_number")]
        public double SequenceNumber { get; set; } = default!;
    }
}