//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: b21cc668ccf9
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    public class OpenResponsesWebSearch20250826ToolFilters
    {
        [JsonProperty("allowed_domains")]
        public List<string>? AllowedDomains { get; set; } = null;
    }
}