//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a731d88ed74c
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class OpenResponsesRequestImageConfigType
    {
        private OpenResponsesRequestImageConfigType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static OpenResponsesRequestImageConfigType Str
        {
            get {
                return new OpenResponsesRequestImageConfigType("str");
            }
        }

        public static OpenResponsesRequestImageConfigType Number
        {
            get {
                return new OpenResponsesRequestImageConfigType("number");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(OpenResponsesRequestImageConfigType v)
        {
            return v.Value;
        }
        public static OpenResponsesRequestImageConfigType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "number":
                    return Number;
                default:
                    throw new ArgumentException("Invalid value for OpenResponsesRequestImageConfigType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OpenResponsesRequestImageConfigType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(OpenResponsesRequestImageConfig.OpenResponsesRequestImageConfigConverter))]
    public class OpenResponsesRequestImageConfig
    {
        public OpenResponsesRequestImageConfig(OpenResponsesRequestImageConfigType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        public OpenResponsesRequestImageConfigType Type { get; set; }
        public static OpenResponsesRequestImageConfig CreateStr(string str)
        {
            OpenResponsesRequestImageConfigType typ = OpenResponsesRequestImageConfigType.Str;

            OpenResponsesRequestImageConfig res = new OpenResponsesRequestImageConfig(typ);
            res.Str = str;
            return res;
        }
        public static OpenResponsesRequestImageConfig CreateNumber(double number)
        {
            OpenResponsesRequestImageConfigType typ = OpenResponsesRequestImageConfigType.Number;

            OpenResponsesRequestImageConfig res = new OpenResponsesRequestImageConfig(typ);
            res.Number = number;
            return res;
        }

        public class OpenResponsesRequestImageConfigConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(OpenResponsesRequestImageConfig);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new OpenResponsesRequestImageConfig(OpenResponsesRequestImageConfigType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new OpenResponsesRequestImageConfig(OpenResponsesRequestImageConfigType.Number) {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                OpenResponsesRequestImageConfig res = (OpenResponsesRequestImageConfig)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }
            }
        }
    }
}