//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0433232af30c
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    public class OpenAIResponsesInputMessage1
    {
        [JsonProperty("type")]
        public OpenAIResponsesInputTypeMessage1? Type { get; set; }

        [JsonProperty("role", NullValueHandling = NullValueHandling.Include)]
        public OpenAIResponsesInputRoleUnion1 Role { get; set; } = default!;

        [JsonProperty("content", NullValueHandling = NullValueHandling.Include)]
        public OpenAIResponsesInputContent2 Content { get; set; } = default!;
    }
}