//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 4a9dc1fa89ca
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Event emitted when function call arguments are being streamed.
    /// </summary>
    public class OpenResponsesStreamEventResponseFunctionCallArgumentsDelta
    {
        [JsonProperty("type")]
        public TypeResponseFunctionCallArgumentsDelta Type { get; set; } = default!;

        [JsonProperty("item_id")]
        public string ItemId { get; set; } = default!;

        [JsonProperty("output_index")]
        public double OutputIndex { get; set; } = default!;

        [JsonProperty("delta")]
        public string Delta { get; set; } = default!;

        [JsonProperty("sequence_number")]
        public double SequenceNumber { get; set; } = default!;
    }
}