//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: eebda3d9431e
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class Part2Type
    {
        private Part2Type(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static Part2Type OutputText
        {
            get {
                return new Part2Type("output_text");
            }
        }

        public static Part2Type ReasoningText
        {
            get {
                return new Part2Type("reasoning_text");
            }
        }

        public static Part2Type Refusal
        {
            get {
                return new Part2Type("refusal");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(Part2Type v)
        {
            return v.Value;
        }
        public static Part2Type FromString(string v)
        {
            switch (v)
            {
                case "output_text":
                    return OutputText;
                case "reasoning_text":
                    return ReasoningText;
                case "refusal":
                    return Refusal;
                default:
                    throw new ArgumentException("Invalid value for Part2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((Part2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(Part2.Part2Converter))]
    public class Part2
    {
        public Part2(Part2Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseOutputText? ResponseOutputText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ReasoningTextContent? ReasoningTextContent { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenAIResponsesRefusalContent? OpenAIResponsesRefusalContent { get; set; }

        public Part2Type Type { get; set; }

        public static Part2 CreateOutputText(ResponseOutputText outputText)
        {
            Part2Type typ = Part2Type.OutputText;
            string typStr = Part2Type.OutputText.ToString();
            outputText.Type = ResponseOutputTextTypeExtension.ToEnum(Part2Type.OutputText.ToString());
            Part2 res = new Part2(typ);
            res.ResponseOutputText = outputText;
            return res;
        }

        public static Part2 CreateReasoningText(ReasoningTextContent reasoningText)
        {
            Part2Type typ = Part2Type.ReasoningText;
            string typStr = Part2Type.ReasoningText.ToString();
            reasoningText.Type = ReasoningTextContentTypeExtension.ToEnum(Part2Type.ReasoningText.ToString());
            Part2 res = new Part2(typ);
            res.ReasoningTextContent = reasoningText;
            return res;
        }

        public static Part2 CreateRefusal(OpenAIResponsesRefusalContent refusal)
        {
            Part2Type typ = Part2Type.Refusal;
            string typStr = Part2Type.Refusal.ToString();
            refusal.Type = OpenAIResponsesRefusalContentTypeExtension.ToEnum(Part2Type.Refusal.ToString());
            Part2 res = new Part2(typ);
            res.OpenAIResponsesRefusalContent = refusal;
            return res;
        }

        public class Part2Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Part2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == Part2Type.OutputText.ToString())
                {
                    ResponseOutputText responseOutputText = ResponseBodyDeserializer.DeserializeNotNull<ResponseOutputText>(jo.ToString());
                    return CreateOutputText(responseOutputText);
                }
                if (discriminator == Part2Type.ReasoningText.ToString())
                {
                    ReasoningTextContent reasoningTextContent = ResponseBodyDeserializer.DeserializeNotNull<ReasoningTextContent>(jo.ToString());
                    return CreateReasoningText(reasoningTextContent);
                }
                if (discriminator == Part2Type.Refusal.ToString())
                {
                    OpenAIResponsesRefusalContent openAIResponsesRefusalContent = ResponseBodyDeserializer.DeserializeNotNull<OpenAIResponsesRefusalContent>(jo.ToString());
                    return CreateRefusal(openAIResponsesRefusalContent);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Part2 res = (Part2)value;

                if (res.ResponseOutputText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseOutputText));
                    return;
                }

                if (res.ReasoningTextContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ReasoningTextContent));
                    return;
                }

                if (res.OpenAIResponsesRefusalContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenAIResponsesRefusalContent));
                    return;
                }
            }
        }
    }
}