//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: fec8ca30a6d7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// Error data for PaymentRequiredResponse.
    /// </summary>
    public class PaymentRequiredResponseErrorData
    {
        [JsonProperty("code")]
        public long Code { get; set; } = default!;

        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        [JsonProperty("metadata")]
        public Dictionary<string, object?>? Metadata { get; set; } = null;
    }
}