//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 13eeb3625acb
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Percentile-based throughput cutoffs. All specified cutoffs must be met for an endpoint to be preferred.
    /// </summary>
    public class PercentileThroughputCutoffs
    {
        /// <summary>
        /// Minimum p50 throughput (tokens/sec).
        /// </summary>
        [JsonProperty("p50")]
        public double? P50 { get; set; } = null;

        /// <summary>
        /// Minimum p75 throughput (tokens/sec).
        /// </summary>
        [JsonProperty("p75")]
        public double? P75 { get; set; } = null;

        /// <summary>
        /// Minimum p90 throughput (tokens/sec).
        /// </summary>
        [JsonProperty("p90")]
        public double? P90 { get; set; } = null;

        /// <summary>
        /// Minimum p99 throughput (tokens/sec).
        /// </summary>
        [JsonProperty("p99")]
        public double? P99 { get; set; } = null;
    }
}