//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0ec9693c5d9d
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Percentile-based latency cutoffs. All specified cutoffs must be met for an endpoint to be preferred.
    /// </summary>
    public class PercentileLatencyCutoffs
    {
        /// <summary>
        /// Maximum p50 latency (seconds).
        /// </summary>
        [JsonProperty("p50")]
        public double? P50 { get; set; } = null;

        /// <summary>
        /// Maximum p75 latency (seconds).
        /// </summary>
        [JsonProperty("p75")]
        public double? P75 { get; set; } = null;

        /// <summary>
        /// Maximum p90 latency (seconds).
        /// </summary>
        [JsonProperty("p90")]
        public double? P90 { get; set; } = null;

        /// <summary>
        /// Maximum p99 latency (seconds).
        /// </summary>
        [JsonProperty("p99")]
        public double? P99 { get; set; } = null;
    }
}