//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a36e287a45cb
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Latency percentiles in milliseconds over the last 30 minutes. Latency measures time to first token. Only visible when authenticated with an API key or cookie; returns null for unauthenticated requests.
    /// </summary>
    public class PercentileStats
    {
        /// <summary>
        /// Median (50th percentile).
        /// </summary>
        [JsonProperty("p50")]
        public double P50 { get; set; } = default!;

        /// <summary>
        /// 75th percentile.
        /// </summary>
        [JsonProperty("p75")]
        public double P75 { get; set; } = default!;

        /// <summary>
        /// 90th percentile.
        /// </summary>
        [JsonProperty("p90")]
        public double P90 { get; set; } = default!;

        /// <summary>
        /// 99th percentile.
        /// </summary>
        [JsonProperty("p99")]
        public double P99 { get; set; } = default!;
    }
}