//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 9819a58d3ea5
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ProviderPreferencesProviderSortConfigUnionType
    {
        private ProviderPreferencesProviderSortConfigUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ProviderPreferencesProviderSortConfigUnionType ProviderPreferencesProviderSortConfig
        {
            get {
                return new ProviderPreferencesProviderSortConfigUnionType("ProviderPreferences_ProviderSortConfig");
            }
        }

        public static ProviderPreferencesProviderSortConfigUnionType ProviderPreferencesProviderSortConfigEnum
        {
            get {
                return new ProviderPreferencesProviderSortConfigUnionType("ProviderPreferences_ProviderSortConfig_enum");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ProviderPreferencesProviderSortConfigUnionType v)
        {
            return v.Value;
        }
        public static ProviderPreferencesProviderSortConfigUnionType FromString(string v)
        {
            switch (v)
            {
                case "ProviderPreferences_ProviderSortConfig":
                    return ProviderPreferencesProviderSortConfig;
                case "ProviderPreferences_ProviderSortConfig_enum":
                    return ProviderPreferencesProviderSortConfigEnum;
                default:
                    throw new ArgumentException("Invalid value for ProviderPreferencesProviderSortConfigUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ProviderPreferencesProviderSortConfigUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The provider sorting strategy (price, throughput, latency).
    /// </summary>
    [JsonConverter(typeof(ProviderPreferencesProviderSortConfigUnion.ProviderPreferencesProviderSortConfigUnionConverter))]
    public class ProviderPreferencesProviderSortConfigUnion
    {
        public ProviderPreferencesProviderSortConfigUnion(ProviderPreferencesProviderSortConfigUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ProviderPreferencesProviderSortConfig? ProviderPreferencesProviderSortConfig { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ProviderPreferencesProviderSortConfigEnum? ProviderPreferencesProviderSortConfigEnum { get; set; }

        public ProviderPreferencesProviderSortConfigUnionType Type { get; set; }
        public static ProviderPreferencesProviderSortConfigUnion CreateProviderPreferencesProviderSortConfig(ProviderPreferencesProviderSortConfig providerPreferencesProviderSortConfig)
        {
            ProviderPreferencesProviderSortConfigUnionType typ = ProviderPreferencesProviderSortConfigUnionType.ProviderPreferencesProviderSortConfig;

            ProviderPreferencesProviderSortConfigUnion res = new ProviderPreferencesProviderSortConfigUnion(typ);
            res.ProviderPreferencesProviderSortConfig = providerPreferencesProviderSortConfig;
            return res;
        }
        public static ProviderPreferencesProviderSortConfigUnion CreateProviderPreferencesProviderSortConfigEnum(ProviderPreferencesProviderSortConfigEnum providerPreferencesProviderSortConfigEnum)
        {
            ProviderPreferencesProviderSortConfigUnionType typ = ProviderPreferencesProviderSortConfigUnionType.ProviderPreferencesProviderSortConfigEnum;

            ProviderPreferencesProviderSortConfigUnion res = new ProviderPreferencesProviderSortConfigUnion(typ);
            res.ProviderPreferencesProviderSortConfigEnum = providerPreferencesProviderSortConfigEnum;
            return res;
        }

        public class ProviderPreferencesProviderSortConfigUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ProviderPreferencesProviderSortConfigUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ProviderPreferencesProviderSortConfigUnion(ProviderPreferencesProviderSortConfigUnionType.ProviderPreferencesProviderSortConfig) {
                        ProviderPreferencesProviderSortConfig = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ProviderPreferencesProviderSortConfig>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ProviderPreferencesProviderSortConfig), new ProviderPreferencesProviderSortConfigUnion(ProviderPreferencesProviderSortConfigUnionType.ProviderPreferencesProviderSortConfig), "ProviderPreferencesProviderSortConfig"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ProviderPreferencesProviderSortConfigUnion(ProviderPreferencesProviderSortConfigUnionType.ProviderPreferencesProviderSortConfigEnum) {
                        ProviderPreferencesProviderSortConfigEnum = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ProviderPreferencesProviderSortConfigEnum>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ProviderPreferencesProviderSortConfigEnum), new ProviderPreferencesProviderSortConfigUnion(ProviderPreferencesProviderSortConfigUnionType.ProviderPreferencesProviderSortConfigEnum), "ProviderPreferencesProviderSortConfigEnum"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ProviderPreferencesProviderSortConfigUnion res = (ProviderPreferencesProviderSortConfigUnion)value;

                if (res.ProviderPreferencesProviderSortConfig != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ProviderPreferencesProviderSortConfig));
                    return;
                }

                if (res.ProviderPreferencesProviderSortConfigEnum != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ProviderPreferencesProviderSortConfigEnum));
                    return;
                }
            }
        }
    }
}