//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 092d47590f88
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Partitioning strategy for sorting: "model" (default) groups endpoints by model before sorting (fallback models remain fallbacks), "none" sorts all endpoints together regardless of model.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ProviderPreferencesPartition : IEquatable<ProviderPreferencesPartition>
    {
        public static readonly ProviderPreferencesPartition Model = new ProviderPreferencesPartition("model");
        public static readonly ProviderPreferencesPartition None = new ProviderPreferencesPartition("none");

        private static readonly Dictionary<string, ProviderPreferencesPartition> _knownValues =
            new Dictionary<string, ProviderPreferencesPartition>() {
                ["model"] = Model,
                ["none"] = None
            };

        private static readonly ConcurrentDictionary<string, ProviderPreferencesPartition> _values =
            new ConcurrentDictionary<string, ProviderPreferencesPartition>(_knownValues);

        private ProviderPreferencesPartition(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ProviderPreferencesPartition Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ProviderPreferencesPartition(value));
        }

        public static implicit operator ProviderPreferencesPartition(string value) => Of(value);
        public static implicit operator string(ProviderPreferencesPartition providerpreferencespartition) => providerpreferencespartition.Value;

        public static ProviderPreferencesPartition[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ProviderPreferencesPartition);

        public bool Equals(ProviderPreferencesPartition? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}