//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 6d9bac989436
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The provider sorting strategy (price, throughput, latency).
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ProviderPreferencesProviderSort : IEquatable<ProviderPreferencesProviderSort>
    {
        public static readonly ProviderPreferencesProviderSort Price = new ProviderPreferencesProviderSort("price");
        public static readonly ProviderPreferencesProviderSort Throughput = new ProviderPreferencesProviderSort("throughput");
        public static readonly ProviderPreferencesProviderSort Latency = new ProviderPreferencesProviderSort("latency");

        private static readonly Dictionary<string, ProviderPreferencesProviderSort> _knownValues =
            new Dictionary<string, ProviderPreferencesProviderSort>() {
                ["price"] = Price,
                ["throughput"] = Throughput,
                ["latency"] = Latency
            };

        private static readonly ConcurrentDictionary<string, ProviderPreferencesProviderSort> _values =
            new ConcurrentDictionary<string, ProviderPreferencesProviderSort>(_knownValues);

        private ProviderPreferencesProviderSort(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ProviderPreferencesProviderSort Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ProviderPreferencesProviderSort(value));
        }

        public static implicit operator ProviderPreferencesProviderSort(string value) => Of(value);
        public static implicit operator string(ProviderPreferencesProviderSort providerpreferencesprovidersort) => providerpreferencesprovidersort.Value;

        public static ProviderPreferencesProviderSort[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ProviderPreferencesProviderSort);

        public bool Equals(ProviderPreferencesProviderSort? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}