//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ab1fbbe9d5e7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Numerics;
    using System.Reflection;

    public class ProviderPreferencesOrderType
    {
        private ProviderPreferencesOrderType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ProviderPreferencesOrderType ProviderName
        {
            get {
                return new ProviderPreferencesOrderType("ProviderName");
            }
        }

        public static ProviderPreferencesOrderType Str
        {
            get {
                return new ProviderPreferencesOrderType("str");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ProviderPreferencesOrderType v)
        {
            return v.Value;
        }
        public static ProviderPreferencesOrderType FromString(string v)
        {
            switch (v)
            {
                case "ProviderName":
                    return ProviderName;
                case "str":
                    return Str;
                default:
                    throw new ArgumentException("Invalid value for ProviderPreferencesOrderType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ProviderPreferencesOrderType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ProviderPreferencesOrder.ProviderPreferencesOrderConverter))]
    public class ProviderPreferencesOrder
    {
        public ProviderPreferencesOrder(ProviderPreferencesOrderType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Models.Components.ProviderName? ProviderName { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        public ProviderPreferencesOrderType Type { get; set; }
        public static ProviderPreferencesOrder CreateProviderName(Models.Components.ProviderName providerName)
        {
            ProviderPreferencesOrderType typ = ProviderPreferencesOrderType.ProviderName;

            ProviderPreferencesOrder res = new ProviderPreferencesOrder(typ);
            res.ProviderName = providerName;
            return res;
        }
        public static ProviderPreferencesOrder CreateStr(string str)
        {
            ProviderPreferencesOrderType typ = ProviderPreferencesOrderType.Str;

            ProviderPreferencesOrder res = new ProviderPreferencesOrder(typ);
            res.Str = str;
            return res;
        }

        public class ProviderPreferencesOrderConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ProviderPreferencesOrder);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ProviderPreferencesOrder(ProviderPreferencesOrderType.ProviderName) {
                        ProviderName = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Models.Components.ProviderName>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Models.Components.ProviderName), new ProviderPreferencesOrder(ProviderPreferencesOrderType.ProviderName), "ProviderName"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new ProviderPreferencesOrder(ProviderPreferencesOrderType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ProviderPreferencesOrder res = (ProviderPreferencesOrder)value;

                if (res.ProviderName != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ProviderName));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
            }
        }
    }
}