//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 197d3b5453a9
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ProviderPreferencesSortEnum : IEquatable<ProviderPreferencesSortEnum>
    {
        public static readonly ProviderPreferencesSortEnum Price = new ProviderPreferencesSortEnum("price");
        public static readonly ProviderPreferencesSortEnum Throughput = new ProviderPreferencesSortEnum("throughput");
        public static readonly ProviderPreferencesSortEnum Latency = new ProviderPreferencesSortEnum("latency");

        private static readonly Dictionary<string, ProviderPreferencesSortEnum> _knownValues =
            new Dictionary<string, ProviderPreferencesSortEnum>() {
                ["price"] = Price,
                ["throughput"] = Throughput,
                ["latency"] = Latency
            };

        private static readonly ConcurrentDictionary<string, ProviderPreferencesSortEnum> _values =
            new ConcurrentDictionary<string, ProviderPreferencesSortEnum>(_knownValues);

        private ProviderPreferencesSortEnum(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ProviderPreferencesSortEnum Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ProviderPreferencesSortEnum(value));
        }

        public static implicit operator ProviderPreferencesSortEnum(string value) => Of(value);
        public static implicit operator string(ProviderPreferencesSortEnum providerpreferencessortenum) => providerpreferencessortenum.Value;

        public static ProviderPreferencesSortEnum[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ProviderPreferencesSortEnum);

        public bool Equals(ProviderPreferencesSortEnum? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}