//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ad237bbf11f7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Numerics;
    using System.Reflection;

    public class ProviderPreferencesOnlyType
    {
        private ProviderPreferencesOnlyType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ProviderPreferencesOnlyType ProviderName
        {
            get {
                return new ProviderPreferencesOnlyType("ProviderName");
            }
        }

        public static ProviderPreferencesOnlyType Str
        {
            get {
                return new ProviderPreferencesOnlyType("str");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ProviderPreferencesOnlyType v)
        {
            return v.Value;
        }
        public static ProviderPreferencesOnlyType FromString(string v)
        {
            switch (v)
            {
                case "ProviderName":
                    return ProviderName;
                case "str":
                    return Str;
                default:
                    throw new ArgumentException("Invalid value for ProviderPreferencesOnlyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ProviderPreferencesOnlyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ProviderPreferencesOnly.ProviderPreferencesOnlyConverter))]
    public class ProviderPreferencesOnly
    {
        public ProviderPreferencesOnly(ProviderPreferencesOnlyType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Models.Components.ProviderName? ProviderName { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        public ProviderPreferencesOnlyType Type { get; set; }
        public static ProviderPreferencesOnly CreateProviderName(Models.Components.ProviderName providerName)
        {
            ProviderPreferencesOnlyType typ = ProviderPreferencesOnlyType.ProviderName;

            ProviderPreferencesOnly res = new ProviderPreferencesOnly(typ);
            res.ProviderName = providerName;
            return res;
        }
        public static ProviderPreferencesOnly CreateStr(string str)
        {
            ProviderPreferencesOnlyType typ = ProviderPreferencesOnlyType.Str;

            ProviderPreferencesOnly res = new ProviderPreferencesOnly(typ);
            res.Str = str;
            return res;
        }

        public class ProviderPreferencesOnlyConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ProviderPreferencesOnly);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ProviderPreferencesOnly(ProviderPreferencesOnlyType.ProviderName) {
                        ProviderName = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Models.Components.ProviderName>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Models.Components.ProviderName), new ProviderPreferencesOnly(ProviderPreferencesOnlyType.ProviderName), "ProviderName"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new ProviderPreferencesOnly(ProviderPreferencesOnlyType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ProviderPreferencesOnly res = (ProviderPreferencesOnly)value;

                if (res.ProviderName != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ProviderName));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
            }
        }
    }
}