//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a6618cb11dd1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Provider routing preferences for the request.
    /// </summary>
    public class ProviderPreferences
    {
        /// <summary>
        /// Whether to allow backup providers to serve requests<br/>
        /// - true: (default) when the primary provider (or your custom providers in "order") is unavailable, use the next best provider.<br/>
        /// - false: use only the primary/custom provider, and return the upstream error if it's unavailable.
        /// </summary>
        [JsonProperty("allow_fallbacks")]
        public bool? AllowFallbacks { get; set; } = null;

        /// <summary>
        /// Whether to filter providers to only those that support the parameters you've provided. If this setting is omitted or set to false, then providers will receive only the parameters they support, and ignore the rest.
        /// </summary>
        [JsonProperty("require_parameters")]
        public bool? RequireParameters { get; set; } = null;

        /// <summary>
        /// Data collection setting. If no available model provider meets the requirement, your request will return an error.<br/>
        /// - allow: (default) allow providers which store user data non-transiently and may train on it<br/>
        /// <br/>
        /// - deny: use only providers which do not collect user data.
        /// </summary>
        [JsonProperty("data_collection")]
        public DataCollection? DataCollection { get; set; } = null;

        /// <summary>
        /// Whether to restrict routing to only ZDR (Zero Data Retention) endpoints. When true, only endpoints that do not retain prompts will be used.
        /// </summary>
        [JsonProperty("zdr")]
        public bool? Zdr { get; set; } = null;

        /// <summary>
        /// Whether to restrict routing to only models that allow text distillation. When true, only models where the author has allowed distillation will be used.
        /// </summary>
        [JsonProperty("enforce_distillable_text")]
        public bool? EnforceDistillableText { get; set; } = null;

        /// <summary>
        /// An ordered list of provider slugs. The router will attempt to use the first provider in the subset of this list that supports your requested model, and fall back to the next if it is unavailable. If no providers are available, the request will fail with an error message.
        /// </summary>
        [JsonProperty("order")]
        public List<ProviderPreferencesOrder>? Order { get; set; } = null;

        /// <summary>
        /// List of provider slugs to allow. If provided, this list is merged with your account-wide allowed provider settings for this request.
        /// </summary>
        [JsonProperty("only")]
        public List<ProviderPreferencesOnly>? Only { get; set; } = null;

        /// <summary>
        /// List of provider slugs to ignore. If provided, this list is merged with your account-wide ignored provider settings for this request.
        /// </summary>
        [JsonProperty("ignore")]
        public List<ProviderPreferencesIgnore>? Ignore { get; set; } = null;

        /// <summary>
        /// A list of quantization levels to filter the provider by.
        /// </summary>
        [JsonProperty("quantizations")]
        public List<Quantization>? Quantizations { get; set; } = null;

        [JsonProperty("sort", NullValueHandling = NullValueHandling.Include)]
        public ProviderPreferencesSortUnion? Sort { get; set; } = null;

        /// <summary>
        /// The object specifying the maximum price you want to pay for this request. USD price per million tokens, for prompt and completion.
        /// </summary>
        [JsonProperty("max_price")]
        public ProviderPreferencesMaxPrice? MaxPrice { get; set; }

        /// <summary>
        /// Preferred minimum throughput (in tokens per second). Can be a number (applies to p50) or an object with percentile-specific cutoffs. Endpoints below the threshold(s) may still be used, but are deprioritized in routing. When using fallback models, this may cause a fallback model to be used instead of the primary model if it meets the threshold.
        /// </summary>
        [JsonProperty("preferred_min_throughput", NullValueHandling = NullValueHandling.Include)]
        public PreferredMinThroughput? PreferredMinThroughput { get; set; } = null;

        /// <summary>
        /// Preferred maximum latency (in seconds). Can be a number (applies to p50) or an object with percentile-specific cutoffs. Endpoints above the threshold(s) may still be used, but are deprioritized in routing. When using fallback models, this may cause a fallback model to be used instead of the primary model if it meets the threshold.
        /// </summary>
        [JsonProperty("preferred_max_latency", NullValueHandling = NullValueHandling.Include)]
        public PreferredMaxLatency? PreferredMaxLatency { get; set; } = null;
    }
}