//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 73fe6fb709ea
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// The object specifying the maximum price you want to pay for this request. USD price per million tokens, for prompt and completion.
    /// </summary>
    public class ProviderPreferencesMaxPrice
    {
        /// <summary>
        /// Price per million prompt tokens.
        /// </summary>
        [JsonProperty("prompt")]
        public string? Prompt { get; set; }

        [JsonProperty("completion")]
        public string? Completion { get; set; }

        [JsonProperty("image")]
        public string? Image { get; set; }

        [JsonProperty("audio")]
        public string? Audio { get; set; }

        [JsonProperty("request")]
        public string? Request { get; set; }
    }
}