//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a458c26d98f2
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Pricing information for the model.
    /// </summary>
    public class PublicPricing
    {
        [JsonProperty("prompt")]
        public string Prompt { get; set; } = default!;

        [JsonProperty("completion")]
        public string Completion { get; set; } = default!;

        [JsonProperty("request")]
        public string? Request { get; set; }

        [JsonProperty("image")]
        public string? Image { get; set; }

        [JsonProperty("image_token")]
        public string? ImageToken { get; set; }

        [JsonProperty("image_output")]
        public string? ImageOutput { get; set; }

        [JsonProperty("audio")]
        public string? Audio { get; set; }

        [JsonProperty("audio_output")]
        public string? AudioOutput { get; set; }

        [JsonProperty("input_audio_cache")]
        public string? InputAudioCache { get; set; }

        [JsonProperty("web_search")]
        public string? WebSearch { get; set; }

        [JsonProperty("internal_reasoning")]
        public string? InternalReasoning { get; set; }

        [JsonProperty("input_cache_read")]
        public string? InputCacheRead { get; set; }

        [JsonProperty("input_cache_write")]
        public string? InputCacheWrite { get; set; }

        [JsonProperty("discount")]
        public double? Discount { get; set; }
    }
}