//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 18f7dcd2c131
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Reasoning detail summary schema.
    /// </summary>
    public class ReasoningDetailSummary
    {
        [JsonProperty("type")]
        public ReasoningDetailSummaryType Type { get; set; } = default!;

        [JsonProperty("summary")]
        public string Summary { get; set; } = default!;

        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        [JsonProperty("format")]
        public ReasoningDetailSummaryFormat? Format { get; set; } = null;

        [JsonProperty("index")]
        public double? Index { get; set; }
    }
}