//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ab8fef4fb1af
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ReasoningSummaryVerbosity : IEquatable<ReasoningSummaryVerbosity>
    {
        public static readonly ReasoningSummaryVerbosity Auto = new ReasoningSummaryVerbosity("auto");
        public static readonly ReasoningSummaryVerbosity Concise = new ReasoningSummaryVerbosity("concise");
        public static readonly ReasoningSummaryVerbosity Detailed = new ReasoningSummaryVerbosity("detailed");

        private static readonly Dictionary<string, ReasoningSummaryVerbosity> _knownValues =
            new Dictionary<string, ReasoningSummaryVerbosity>() {
                ["auto"] = Auto,
                ["concise"] = Concise,
                ["detailed"] = Detailed
            };

        private static readonly ConcurrentDictionary<string, ReasoningSummaryVerbosity> _values =
            new ConcurrentDictionary<string, ReasoningSummaryVerbosity>(_knownValues);

        private ReasoningSummaryVerbosity(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ReasoningSummaryVerbosity Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ReasoningSummaryVerbosity(value));
        }

        public static implicit operator ReasoningSummaryVerbosity(string value) => Of(value);
        public static implicit operator string(ReasoningSummaryVerbosity reasoningsummaryverbosity) => reasoningsummaryverbosity.Value;

        public static ReasoningSummaryVerbosity[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ReasoningSummaryVerbosity);

        public bool Equals(ReasoningSummaryVerbosity? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}