//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 5a8cceecf8a2
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ReasoningDetailSummaryFormat : IEquatable<ReasoningDetailSummaryFormat>
    {
        public static readonly ReasoningDetailSummaryFormat Unknown = new ReasoningDetailSummaryFormat("unknown");
        public static readonly ReasoningDetailSummaryFormat OpenaiResponsesV1 = new ReasoningDetailSummaryFormat("openai-responses-v1");
        public static readonly ReasoningDetailSummaryFormat AzureOpenaiResponsesV1 = new ReasoningDetailSummaryFormat("azure-openai-responses-v1");
        public static readonly ReasoningDetailSummaryFormat XaiResponsesV1 = new ReasoningDetailSummaryFormat("xai-responses-v1");
        public static readonly ReasoningDetailSummaryFormat AnthropicClaudeV1 = new ReasoningDetailSummaryFormat("anthropic-claude-v1");
        public static readonly ReasoningDetailSummaryFormat GoogleGeminiV1 = new ReasoningDetailSummaryFormat("google-gemini-v1");

        private static readonly Dictionary<string, ReasoningDetailSummaryFormat> _knownValues =
            new Dictionary<string, ReasoningDetailSummaryFormat>() {
                ["unknown"] = Unknown,
                ["openai-responses-v1"] = OpenaiResponsesV1,
                ["azure-openai-responses-v1"] = AzureOpenaiResponsesV1,
                ["xai-responses-v1"] = XaiResponsesV1,
                ["anthropic-claude-v1"] = AnthropicClaudeV1,
                ["google-gemini-v1"] = GoogleGeminiV1
            };

        private static readonly ConcurrentDictionary<string, ReasoningDetailSummaryFormat> _values =
            new ConcurrentDictionary<string, ReasoningDetailSummaryFormat>(_knownValues);

        private ReasoningDetailSummaryFormat(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ReasoningDetailSummaryFormat Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ReasoningDetailSummaryFormat(value));
        }

        public static implicit operator ReasoningDetailSummaryFormat(string value) => Of(value);
        public static implicit operator string(ReasoningDetailSummaryFormat reasoningdetailsummaryformat) => reasoningdetailsummaryformat.Value;

        public static ReasoningDetailSummaryFormat[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ReasoningDetailSummaryFormat);

        public bool Equals(ReasoningDetailSummaryFormat? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}