//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 078cd54a55e2
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ResponseFormatType
    {
        private ResponseFormatType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ResponseFormatType Text
        {
            get {
                return new ResponseFormatType("text");
            }
        }

        public static ResponseFormatType JsonObject
        {
            get {
                return new ResponseFormatType("json_object");
            }
        }

        public static ResponseFormatType JsonSchema
        {
            get {
                return new ResponseFormatType("json_schema");
            }
        }

        public static ResponseFormatType Grammar
        {
            get {
                return new ResponseFormatType("grammar");
            }
        }

        public static ResponseFormatType Python
        {
            get {
                return new ResponseFormatType("python");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ResponseFormatType v)
        {
            return v.Value;
        }
        public static ResponseFormatType FromString(string v)
        {
            switch (v)
            {
                case "text":
                    return Text;
                case "json_object":
                    return JsonObject;
                case "json_schema":
                    return JsonSchema;
                case "grammar":
                    return Grammar;
                case "python":
                    return Python;
                default:
                    throw new ArgumentException("Invalid value for ResponseFormatType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseFormatType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Response format configuration.
    /// </summary>
    [JsonConverter(typeof(ResponseFormat.ResponseFormatConverter))]
    public class ResponseFormat
    {
        public ResponseFormat(ResponseFormatType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormatText? ResponseFormatText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormatJSONObject? ResponseFormatJSONObject { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormatJSONSchema? ResponseFormatJSONSchema { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormatTextGrammar? ResponseFormatTextGrammar { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormatTextPython? ResponseFormatTextPython { get; set; }

        public ResponseFormatType Type { get; set; }

        public static ResponseFormat CreateText(ResponseFormatText text)
        {
            ResponseFormatType typ = ResponseFormatType.Text;
            string typStr = ResponseFormatType.Text.ToString();
            text.Type = ResponseFormatTextTypeExtension.ToEnum(ResponseFormatType.Text.ToString());
            ResponseFormat res = new ResponseFormat(typ);
            res.ResponseFormatText = text;
            return res;
        }

        public static ResponseFormat CreateJsonObject(ResponseFormatJSONObject jsonObject)
        {
            ResponseFormatType typ = ResponseFormatType.JsonObject;
            string typStr = ResponseFormatType.JsonObject.ToString();
            jsonObject.Type = ResponseFormatJSONObjectTypeExtension.ToEnum(ResponseFormatType.JsonObject.ToString());
            ResponseFormat res = new ResponseFormat(typ);
            res.ResponseFormatJSONObject = jsonObject;
            return res;
        }

        public static ResponseFormat CreateJsonSchema(ResponseFormatJSONSchema jsonSchema)
        {
            ResponseFormatType typ = ResponseFormatType.JsonSchema;
            string typStr = ResponseFormatType.JsonSchema.ToString();
            jsonSchema.Type = ResponseFormatJSONSchemaTypeExtension.ToEnum(ResponseFormatType.JsonSchema.ToString());
            ResponseFormat res = new ResponseFormat(typ);
            res.ResponseFormatJSONSchema = jsonSchema;
            return res;
        }

        public static ResponseFormat CreateGrammar(ResponseFormatTextGrammar grammar)
        {
            ResponseFormatType typ = ResponseFormatType.Grammar;
            string typStr = ResponseFormatType.Grammar.ToString();
            grammar.Type = ResponseFormatTextGrammarTypeExtension.ToEnum(ResponseFormatType.Grammar.ToString());
            ResponseFormat res = new ResponseFormat(typ);
            res.ResponseFormatTextGrammar = grammar;
            return res;
        }

        public static ResponseFormat CreatePython(ResponseFormatTextPython python)
        {
            ResponseFormatType typ = ResponseFormatType.Python;
            string typStr = ResponseFormatType.Python.ToString();
            python.Type = ResponseFormatTextPythonTypeExtension.ToEnum(ResponseFormatType.Python.ToString());
            ResponseFormat res = new ResponseFormat(typ);
            res.ResponseFormatTextPython = python;
            return res;
        }

        public class ResponseFormatConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseFormat);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == ResponseFormatType.Text.ToString())
                {
                    ResponseFormatText responseFormatText = ResponseBodyDeserializer.DeserializeNotNull<ResponseFormatText>(jo.ToString());
                    return CreateText(responseFormatText);
                }
                if (discriminator == ResponseFormatType.JsonObject.ToString())
                {
                    ResponseFormatJSONObject responseFormatJSONObject = ResponseBodyDeserializer.DeserializeNotNull<ResponseFormatJSONObject>(jo.ToString());
                    return CreateJsonObject(responseFormatJSONObject);
                }
                if (discriminator == ResponseFormatType.JsonSchema.ToString())
                {
                    ResponseFormatJSONSchema responseFormatJSONSchema = ResponseBodyDeserializer.DeserializeNotNull<ResponseFormatJSONSchema>(jo.ToString());
                    return CreateJsonSchema(responseFormatJSONSchema);
                }
                if (discriminator == ResponseFormatType.Grammar.ToString())
                {
                    ResponseFormatTextGrammar responseFormatTextGrammar = ResponseBodyDeserializer.DeserializeNotNull<ResponseFormatTextGrammar>(jo.ToString());
                    return CreateGrammar(responseFormatTextGrammar);
                }
                if (discriminator == ResponseFormatType.Python.ToString())
                {
                    ResponseFormatTextPython responseFormatTextPython = ResponseBodyDeserializer.DeserializeNotNull<ResponseFormatTextPython>(jo.ToString());
                    return CreatePython(responseFormatTextPython);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ResponseFormat res = (ResponseFormat)value;

                if (res.ResponseFormatText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormatText));
                    return;
                }

                if (res.ResponseFormatJSONObject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormatJSONObject));
                    return;
                }

                if (res.ResponseFormatJSONSchema != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormatJSONSchema));
                    return;
                }

                if (res.ResponseFormatTextGrammar != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormatTextGrammar));
                    return;
                }

                if (res.ResponseFormatTextPython != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormatTextPython));
                    return;
                }
            }
        }
    }
}