//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 9f6e651ed3ac
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ResponseFormatTextConfigType
    {
        private ResponseFormatTextConfigType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ResponseFormatTextConfigType Text
        {
            get {
                return new ResponseFormatTextConfigType("text");
            }
        }

        public static ResponseFormatTextConfigType JsonObject
        {
            get {
                return new ResponseFormatTextConfigType("json_object");
            }
        }

        public static ResponseFormatTextConfigType JsonSchema
        {
            get {
                return new ResponseFormatTextConfigType("json_schema");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ResponseFormatTextConfigType v)
        {
            return v.Value;
        }
        public static ResponseFormatTextConfigType FromString(string v)
        {
            switch (v)
            {
                case "text":
                    return Text;
                case "json_object":
                    return JsonObject;
                case "json_schema":
                    return JsonSchema;
                default:
                    throw new ArgumentException("Invalid value for ResponseFormatTextConfigType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseFormatTextConfigType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Text response format configuration.
    /// </summary>
    [JsonConverter(typeof(ResponseFormatTextConfig.ResponseFormatTextConfigConverter))]
    public class ResponseFormatTextConfig
    {
        public ResponseFormatTextConfig(ResponseFormatTextConfigType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponsesFormatText? ResponsesFormatText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseFormatJSONObject? ResponseFormatJSONObject { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponsesFormatTextJSONSchemaConfig? ResponsesFormatTextJSONSchemaConfig { get; set; }

        public ResponseFormatTextConfigType Type { get; set; }

        public static ResponseFormatTextConfig CreateText(ResponsesFormatText text)
        {
            ResponseFormatTextConfigType typ = ResponseFormatTextConfigType.Text;
            string typStr = ResponseFormatTextConfigType.Text.ToString();
            text.Type = ResponsesFormatTextTypeExtension.ToEnum(ResponseFormatTextConfigType.Text.ToString());
            ResponseFormatTextConfig res = new ResponseFormatTextConfig(typ);
            res.ResponsesFormatText = text;
            return res;
        }

        public static ResponseFormatTextConfig CreateJsonObject(ResponseFormatJSONObject jsonObject)
        {
            ResponseFormatTextConfigType typ = ResponseFormatTextConfigType.JsonObject;
            string typStr = ResponseFormatTextConfigType.JsonObject.ToString();
            jsonObject.Type = ResponseFormatJSONObjectTypeExtension.ToEnum(ResponseFormatTextConfigType.JsonObject.ToString());
            ResponseFormatTextConfig res = new ResponseFormatTextConfig(typ);
            res.ResponseFormatJSONObject = jsonObject;
            return res;
        }

        public static ResponseFormatTextConfig CreateJsonSchema(ResponsesFormatTextJSONSchemaConfig jsonSchema)
        {
            ResponseFormatTextConfigType typ = ResponseFormatTextConfigType.JsonSchema;
            string typStr = ResponseFormatTextConfigType.JsonSchema.ToString();
            jsonSchema.Type = ResponsesFormatTextJSONSchemaConfigTypeExtension.ToEnum(ResponseFormatTextConfigType.JsonSchema.ToString());
            ResponseFormatTextConfig res = new ResponseFormatTextConfig(typ);
            res.ResponsesFormatTextJSONSchemaConfig = jsonSchema;
            return res;
        }

        public class ResponseFormatTextConfigConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseFormatTextConfig);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == ResponseFormatTextConfigType.Text.ToString())
                {
                    ResponsesFormatText responsesFormatText = ResponseBodyDeserializer.DeserializeNotNull<ResponsesFormatText>(jo.ToString());
                    return CreateText(responsesFormatText);
                }
                if (discriminator == ResponseFormatTextConfigType.JsonObject.ToString())
                {
                    ResponseFormatJSONObject responseFormatJSONObject = ResponseBodyDeserializer.DeserializeNotNull<ResponseFormatJSONObject>(jo.ToString());
                    return CreateJsonObject(responseFormatJSONObject);
                }
                if (discriminator == ResponseFormatTextConfigType.JsonSchema.ToString())
                {
                    ResponsesFormatTextJSONSchemaConfig responsesFormatTextJSONSchemaConfig = ResponseBodyDeserializer.DeserializeNotNull<ResponsesFormatTextJSONSchemaConfig>(jo.ToString());
                    return CreateJsonSchema(responsesFormatTextJSONSchemaConfig);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ResponseFormatTextConfig res = (ResponseFormatTextConfig)value;

                if (res.ResponsesFormatText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponsesFormatText));
                    return;
                }

                if (res.ResponseFormatJSONObject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseFormatJSONObject));
                    return;
                }

                if (res.ResponsesFormatTextJSONSchemaConfig != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponsesFormatTextJSONSchemaConfig));
                    return;
                }
            }
        }
    }
}