//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a6f41da18350
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ResponsesOutputMessageContentType
    {
        private ResponsesOutputMessageContentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ResponsesOutputMessageContentType OutputText
        {
            get {
                return new ResponsesOutputMessageContentType("output_text");
            }
        }

        public static ResponsesOutputMessageContentType Refusal
        {
            get {
                return new ResponsesOutputMessageContentType("refusal");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ResponsesOutputMessageContentType v)
        {
            return v.Value;
        }
        public static ResponsesOutputMessageContentType FromString(string v)
        {
            switch (v)
            {
                case "output_text":
                    return OutputText;
                case "refusal":
                    return Refusal;
                default:
                    throw new ArgumentException("Invalid value for ResponsesOutputMessageContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponsesOutputMessageContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(ResponsesOutputMessageContent.ResponsesOutputMessageContentConverter))]
    public class ResponsesOutputMessageContent
    {
        public ResponsesOutputMessageContent(ResponsesOutputMessageContentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ResponseOutputText? ResponseOutputText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public OpenAIResponsesRefusalContent? OpenAIResponsesRefusalContent { get; set; }

        public ResponsesOutputMessageContentType Type { get; set; }

        public static ResponsesOutputMessageContent CreateOutputText(ResponseOutputText outputText)
        {
            ResponsesOutputMessageContentType typ = ResponsesOutputMessageContentType.OutputText;
            string typStr = ResponsesOutputMessageContentType.OutputText.ToString();
            outputText.Type = ResponseOutputTextTypeExtension.ToEnum(ResponsesOutputMessageContentType.OutputText.ToString());
            ResponsesOutputMessageContent res = new ResponsesOutputMessageContent(typ);
            res.ResponseOutputText = outputText;
            return res;
        }

        public static ResponsesOutputMessageContent CreateRefusal(OpenAIResponsesRefusalContent refusal)
        {
            ResponsesOutputMessageContentType typ = ResponsesOutputMessageContentType.Refusal;
            string typStr = ResponsesOutputMessageContentType.Refusal.ToString();
            refusal.Type = OpenAIResponsesRefusalContentTypeExtension.ToEnum(ResponsesOutputMessageContentType.Refusal.ToString());
            ResponsesOutputMessageContent res = new ResponsesOutputMessageContent(typ);
            res.OpenAIResponsesRefusalContent = refusal;
            return res;
        }

        public class ResponsesOutputMessageContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponsesOutputMessageContent);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == ResponsesOutputMessageContentType.OutputText.ToString())
                {
                    ResponseOutputText responseOutputText = ResponseBodyDeserializer.DeserializeNotNull<ResponseOutputText>(jo.ToString());
                    return CreateOutputText(responseOutputText);
                }
                if (discriminator == ResponsesOutputMessageContentType.Refusal.ToString())
                {
                    OpenAIResponsesRefusalContent openAIResponsesRefusalContent = ResponseBodyDeserializer.DeserializeNotNull<OpenAIResponsesRefusalContent>(jo.ToString());
                    return CreateRefusal(openAIResponsesRefusalContent);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ResponsesOutputMessageContent res = (ResponsesOutputMessageContent)value;

                if (res.ResponseOutputText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ResponseOutputText));
                    return;
                }

                if (res.OpenAIResponsesRefusalContent != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OpenAIResponsesRefusalContent));
                    return;
                }
            }
        }
    }
}