//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: d44d65ad6469
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum ResponsesFormatTextJSONSchemaConfigType
    {
        [JsonProperty("json_schema")] JsonSchema,
    }

    public static class ResponsesFormatTextJSONSchemaConfigTypeExtension
    {
        public static string Value(this ResponsesFormatTextJSONSchemaConfigType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ResponsesFormatTextJSONSchemaConfigType ToEnum(this string value)
        {
            foreach (var field in typeof(ResponsesFormatTextJSONSchemaConfigType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ResponsesFormatTextJSONSchemaConfigType)
                    {
                        return (ResponsesFormatTextJSONSchemaConfigType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ResponsesFormatTextJSONSchemaConfigType");
        }
    }
}