//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 279474e34bc9
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ResponseInputAudioFormat : IEquatable<ResponseInputAudioFormat>
    {
        public static readonly ResponseInputAudioFormat Mp3 = new ResponseInputAudioFormat("mp3");
        public static readonly ResponseInputAudioFormat Wav = new ResponseInputAudioFormat("wav");

        private static readonly Dictionary<string, ResponseInputAudioFormat> _knownValues =
            new Dictionary<string, ResponseInputAudioFormat>() {
                ["mp3"] = Mp3,
                ["wav"] = Wav
            };

        private static readonly ConcurrentDictionary<string, ResponseInputAudioFormat> _values =
            new ConcurrentDictionary<string, ResponseInputAudioFormat>(_knownValues);

        private ResponseInputAudioFormat(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ResponseInputAudioFormat Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ResponseInputAudioFormat(value));
        }

        public static implicit operator ResponseInputAudioFormat(string value) => Of(value);
        public static implicit operator string(ResponseInputAudioFormat responseinputaudioformat) => responseinputaudioformat.Value;

        public static ResponseInputAudioFormat[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ResponseInputAudioFormat);

        public bool Equals(ResponseInputAudioFormat? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}