//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 9d231dd0e46a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// File input content item.
    /// </summary>
    public class ResponseInputFile
    {
        [JsonProperty("type")]
        public ResponseInputFileType Type { get; set; } = default!;

        [JsonProperty("file_id")]
        public string? FileId { get; set; } = null;

        [JsonProperty("file_data")]
        public string? FileData { get; set; }

        [JsonProperty("filename")]
        public string? Filename { get; set; }

        [JsonProperty("file_url")]
        public string? FileUrl { get; set; }
    }
}