//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 694318c63d3f
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ResponseTextConfigVerbosity : IEquatable<ResponseTextConfigVerbosity>
    {
        public static readonly ResponseTextConfigVerbosity High = new ResponseTextConfigVerbosity("high");
        public static readonly ResponseTextConfigVerbosity Low = new ResponseTextConfigVerbosity("low");
        public static readonly ResponseTextConfigVerbosity Medium = new ResponseTextConfigVerbosity("medium");

        private static readonly Dictionary<string, ResponseTextConfigVerbosity> _knownValues =
            new Dictionary<string, ResponseTextConfigVerbosity>() {
                ["high"] = High,
                ["low"] = Low,
                ["medium"] = Medium
            };

        private static readonly ConcurrentDictionary<string, ResponseTextConfigVerbosity> _values =
            new ConcurrentDictionary<string, ResponseTextConfigVerbosity>(_knownValues);

        private ResponseTextConfigVerbosity(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ResponseTextConfigVerbosity Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ResponseTextConfigVerbosity(value));
        }

        public static implicit operator ResponseTextConfigVerbosity(string value) => Of(value);
        public static implicit operator string(ResponseTextConfigVerbosity responsetextconfigverbosity) => responsetextconfigverbosity.Value;

        public static ResponseTextConfigVerbosity[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ResponseTextConfigVerbosity);

        public bool Equals(ResponseTextConfigVerbosity? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}