//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: beb2113fc84b
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class StopType
    {
        private StopType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static StopType Str
        {
            get {
                return new StopType("str");
            }
        }

        public static StopType ArrayOfStr
        {
            get {
                return new StopType("arrayOfStr");
            }
        }

        public static StopType Any
        {
            get {
                return new StopType("any");
            }
        }

        public static StopType Null
        {
            get {
                return new StopType("null");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(StopType v)
        {
            return v.Value;
        }
        public static StopType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "arrayOfStr":
                    return ArrayOfStr;
                case "any":
                    return Any;
                case "null":
                    return Null;
                default:
                    throw new ArgumentException("Invalid value for StopType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((StopType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Stop sequences (up to 4).
    /// </summary>
    [JsonConverter(typeof(Stop.StopConverter))]
    public class Stop
    {
        public Stop(StopType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public object? Any { get; set; }

        public StopType Type { get; set; }
        public static Stop CreateStr(string str)
        {
            StopType typ = StopType.Str;

            Stop res = new Stop(typ);
            res.Str = str;
            return res;
        }
        public static Stop CreateArrayOfStr(List<string> arrayOfStr)
        {
            StopType typ = StopType.ArrayOfStr;

            Stop res = new Stop(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }
        public static Stop CreateAny(object any)
        {
            StopType typ = StopType.Any;

            Stop res = new Stop(typ);
            res.Any = any;
            return res;
        }

        public static Stop CreateNull()
        {
            StopType typ = StopType.Null;
            return new Stop(typ);
        }

        public class StopConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Stop);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new Stop(StopType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                try
                {
                    return new Stop(StopType.ArrayOfStr) {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new Stop(StopType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Stop(StopType.Any) {
                        Any = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<object>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(object), new Stop(StopType.Any), "Any"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                Stop res = (Stop)value;
                if (StopType.FromString(res.Type).Equals(StopType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }

                if (res.Any != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Any));
                    return;
                }
            }
        }
    }
}