//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 686b67cc64a0
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Tokenizer type used by the model.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class Tokenizer : IEquatable<Tokenizer>
    {
        public static readonly Tokenizer Router = new Tokenizer("Router");
        public static readonly Tokenizer Media = new Tokenizer("Media");
        public static readonly Tokenizer Other = new Tokenizer("Other");
        public static readonly Tokenizer Gpt = new Tokenizer("GPT");
        public static readonly Tokenizer Claude = new Tokenizer("Claude");
        public static readonly Tokenizer Gemini = new Tokenizer("Gemini");
        public static readonly Tokenizer Grok = new Tokenizer("Grok");
        public static readonly Tokenizer Cohere = new Tokenizer("Cohere");
        public static readonly Tokenizer Nova = new Tokenizer("Nova");
        public static readonly Tokenizer Qwen = new Tokenizer("Qwen");
        public static readonly Tokenizer Yi = new Tokenizer("Yi");
        public static readonly Tokenizer DeepSeek = new Tokenizer("DeepSeek");
        public static readonly Tokenizer Mistral = new Tokenizer("Mistral");
        public static readonly Tokenizer Llama2 = new Tokenizer("Llama2");
        public static readonly Tokenizer Llama3 = new Tokenizer("Llama3");
        public static readonly Tokenizer Llama4 = new Tokenizer("Llama4");
        public static readonly Tokenizer PaLM = new Tokenizer("PaLM");
        public static readonly Tokenizer Rwkv = new Tokenizer("RWKV");
        public static readonly Tokenizer Qwen3 = new Tokenizer("Qwen3");

        private static readonly Dictionary<string, Tokenizer> _knownValues =
            new Dictionary<string, Tokenizer>() {
                ["Router"] = Router,
                ["Media"] = Media,
                ["Other"] = Other,
                ["GPT"] = Gpt,
                ["Claude"] = Claude,
                ["Gemini"] = Gemini,
                ["Grok"] = Grok,
                ["Cohere"] = Cohere,
                ["Nova"] = Nova,
                ["Qwen"] = Qwen,
                ["Yi"] = Yi,
                ["DeepSeek"] = DeepSeek,
                ["Mistral"] = Mistral,
                ["Llama2"] = Llama2,
                ["Llama3"] = Llama3,
                ["Llama4"] = Llama4,
                ["PaLM"] = PaLM,
                ["RWKV"] = Rwkv,
                ["Qwen3"] = Qwen3
            };

        private static readonly ConcurrentDictionary<string, Tokenizer> _values =
            new ConcurrentDictionary<string, Tokenizer>(_knownValues);

        private Tokenizer(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Tokenizer Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new Tokenizer(value));
        }

        public static implicit operator Tokenizer(string value) => Of(value);
        public static implicit operator string(Tokenizer tokenizer) => tokenizer.Value;

        public static Tokenizer[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Tokenizer);

        public bool Equals(Tokenizer? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}