//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 5ec05e524cd5
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Tool response message.
    /// </summary>
    public class ToolResponseMessage
    {
        [JsonProperty("role")]
        public ToolResponseMessageRole Role { get; set; } = default!;

        /// <summary>
        /// Tool response content.
        /// </summary>
        [JsonProperty("content", NullValueHandling = NullValueHandling.Include)]
        public ToolResponseMessageContent Content { get; set; } = default!;

        /// <summary>
        /// ID of the assistant message tool call this message responds to.
        /// </summary>
        [JsonProperty("tool_call_id")]
        public string ToolCallId { get; set; } = default!;
    }
}