//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: c18ceda265aa
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ToolResponseMessageContentType
    {
        private ToolResponseMessageContentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ToolResponseMessageContentType Str
        {
            get {
                return new ToolResponseMessageContentType("str");
            }
        }

        public static ToolResponseMessageContentType ArrayOfChatMessageContentItem
        {
            get {
                return new ToolResponseMessageContentType("arrayOfChatMessageContentItem");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ToolResponseMessageContentType v)
        {
            return v.Value;
        }
        public static ToolResponseMessageContentType FromString(string v)
        {
            switch (v)
            {
                case "str":
                    return Str;
                case "arrayOfChatMessageContentItem":
                    return ArrayOfChatMessageContentItem;
                default:
                    throw new ArgumentException("Invalid value for ToolResponseMessageContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ToolResponseMessageContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Tool response content.
    /// </summary>
    [JsonConverter(typeof(ToolResponseMessageContent.ToolResponseMessageContentConverter))]
    public class ToolResponseMessageContent
    {
        public ToolResponseMessageContent(ToolResponseMessageContentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<ChatMessageContentItem>? ArrayOfChatMessageContentItem { get; set; }

        public ToolResponseMessageContentType Type { get; set; }
        public static ToolResponseMessageContent CreateStr(string str)
        {
            ToolResponseMessageContentType typ = ToolResponseMessageContentType.Str;

            ToolResponseMessageContent res = new ToolResponseMessageContent(typ);
            res.Str = str;
            return res;
        }
        public static ToolResponseMessageContent CreateArrayOfChatMessageContentItem(List<ChatMessageContentItem> arrayOfChatMessageContentItem)
        {
            ToolResponseMessageContentType typ = ToolResponseMessageContentType.ArrayOfChatMessageContentItem;

            ToolResponseMessageContent res = new ToolResponseMessageContent(typ);
            res.ArrayOfChatMessageContentItem = arrayOfChatMessageContentItem;
            return res;
        }

        public class ToolResponseMessageContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ToolResponseMessageContent);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new ToolResponseMessageContent(ToolResponseMessageContentType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                try
                {
                    return new ToolResponseMessageContent(ToolResponseMessageContentType.ArrayOfChatMessageContentItem) {
                        ArrayOfChatMessageContentItem = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<ChatMessageContentItem>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<ChatMessageContentItem>), new ToolResponseMessageContent(ToolResponseMessageContentType.ArrayOfChatMessageContentItem), "ArrayOfChatMessageContentItem"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ToolResponseMessageContent res = (ToolResponseMessageContent)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.ArrayOfChatMessageContentItem != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfChatMessageContentItem));
                    return;
                }
            }
        }
    }
}