//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 6c0007f53ad9
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class Truncation : IEquatable<Truncation>
    {
        public static readonly Truncation Auto = new Truncation("auto");
        public static readonly Truncation Disabled = new Truncation("disabled");

        private static readonly Dictionary<string, Truncation> _knownValues =
            new Dictionary<string, Truncation>() {
                ["auto"] = Auto,
                ["disabled"] = Disabled
            };

        private static readonly ConcurrentDictionary<string, Truncation> _values =
            new ConcurrentDictionary<string, Truncation>(_knownValues);

        private Truncation(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Truncation Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new Truncation(value));
        }

        public static implicit operator Truncation(string value) => Of(value);
        public static implicit operator string(Truncation truncation) => truncation.Value;

        public static Truncation[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Truncation);

        public bool Equals(Truncation? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}