//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7a16b463f3b5
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum TypeResponseIncomplete
    {
        [JsonProperty("response.incomplete")] ResponseIncomplete,
    }

    public static class TypeResponseIncompleteExtension
    {
        public static string Value(this TypeResponseIncomplete value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TypeResponseIncomplete ToEnum(this string value)
        {
            foreach (var field in typeof(TypeResponseIncomplete).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TypeResponseIncomplete)
                    {
                        return (TypeResponseIncomplete)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TypeResponseIncomplete");
        }
    }
}