//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 0e95d7408aff
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum TypeResponseFunctionCallArgumentsDone
    {
        [JsonProperty("response.function_call_arguments.done")] ResponseFunctionCallArgumentsDone,
    }

    public static class TypeResponseFunctionCallArgumentsDoneExtension
    {
        public static string Value(this TypeResponseFunctionCallArgumentsDone value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TypeResponseFunctionCallArgumentsDone ToEnum(this string value)
        {
            foreach (var field in typeof(TypeResponseFunctionCallArgumentsDone).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TypeResponseFunctionCallArgumentsDone)
                    {
                        return (TypeResponseFunctionCallArgumentsDone)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TypeResponseFunctionCallArgumentsDone");
        }
    }
}