//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 8026fb524960
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum TypeResponseOutputTextAnnotationAdded
    {
        [JsonProperty("response.output_text.annotation.added")] ResponseOutputTextAnnotationAdded,
    }

    public static class TypeResponseOutputTextAnnotationAddedExtension
    {
        public static string Value(this TypeResponseOutputTextAnnotationAdded value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TypeResponseOutputTextAnnotationAdded ToEnum(this string value)
        {
            foreach (var field in typeof(TypeResponseOutputTextAnnotationAdded).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TypeResponseOutputTextAnnotationAdded)
                    {
                        return (TypeResponseOutputTextAnnotationAdded)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TypeResponseOutputTextAnnotationAdded");
        }
    }
}