//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7f9e1e51f66b
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Components
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    public class URLCitation
    {
        [JsonProperty("type")]
        public URLCitationType Type { get; set; } = default!;

        [JsonProperty("url")]
        public string Url { get; set; } = default!;

        [JsonProperty("title")]
        public string Title { get; set; } = default!;

        [JsonProperty("start_index")]
        public double StartIndex { get; set; } = default!;

        [JsonProperty("end_index")]
        public double EndIndex { get; set; } = default!;
    }
}