//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 7b1cde9aa74b
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace OpenRouterSDK.Models.Errors
{
    using System;
    using System.Net.Http;

    /// <summary>
    /// Raised if the response data could not be deserialized into the expected model.
    /// </summary>
    public class ResponseValidationException : OpenRouterException
    {

        public ResponseValidationException(
            string message,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body,
            Exception innerException
        ) : base(message, request, response, body, innerException)
        {
        }
    }
}
