//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: f0bf2a46142d
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Errors
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;
    using System;
    using System.Net.Http;

    public class TooManyRequestsResponseExceptionPayload
    {
        /// <summary>
        /// Error data for TooManyRequestsResponse.
        /// </summary>
        [JsonProperty("error")]
        public TooManyRequestsResponseErrorData Error { get; set; } = default!;

        [JsonProperty("user_id")]
        public string? UserId { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// Too Many Requests - Rate limit exceeded.
    /// </summary>
    public class TooManyRequestsResponseException : OpenRouterException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public TooManyRequestsResponseExceptionPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use TooManyRequestsResponseException.Payload.Error instead.")]
        public TooManyRequestsResponseErrorData Error { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use TooManyRequestsResponseException.Payload.UserId instead.")]
        public string? UserId { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use TooManyRequestsResponseException.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        private static string ErrorMessage(TooManyRequestsResponseExceptionPayload payload, string body)
        {
            string? message = payload.Error?.Message;
            if (!string.IsNullOrEmpty(message))
            {
                return message;
            }

            return "API error occurred";
        }

        public TooManyRequestsResponseException(
            TooManyRequestsResponseExceptionPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ) : base(ErrorMessage(payload, body), request, response, body)
        {
            Payload = payload;

#pragma warning disable CS0618
            Error = payload.Error;
            UserId = payload.UserId;
            HttpMeta = payload.HttpMeta;
#pragma warning restore CS0618
        }
    }
}