//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 6173e6570d02
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Hooks;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Models.Errors;
    using OpenRouterSDK.Utils;
    using OpenRouterSDK.Utils.Retries;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    /// <summary>
    /// OpenRouter API: OpenAI-compatible API with additional OpenRouter features<br/>
    /// <see href="https://openrouter.ai/docs">OpenRouter Documentation</see>
    /// </summary>
    public interface IOpenRouter
    {
        public IBeta Beta { get; }

        /// <summary>
        /// Analytics and usage endpoints.
        /// </summary>
        public IAnalytics Analytics { get; }

        public IChat Chat { get; }

        /// <summary>
        /// Credit management endpoints.
        /// </summary>
        public ICredits Credits { get; }

        /// <summary>
        /// Text embedding endpoints.
        /// </summary>
        public IEmbeddings Embeddings { get; }

        /// <summary>
        /// Generation history endpoints.
        /// </summary>
        public IGenerations Generations { get; }

        public IAIModels AIModels { get; }

        /// <summary>
        /// Endpoint information.
        /// </summary>
        public IEndpoints Endpoints { get; }

        /// <summary>
        /// Provider information endpoints.
        /// </summary>
        public IProviders Providers { get; }

        /// <summary>
        /// API key management endpoints.
        /// </summary>
        public IAPIKeys APIKeys { get; }

        /// <summary>
        /// Guardrails endpoints.
        /// </summary>
        public IGuardrails Guardrails { get; }

        /// <summary>
        /// OAuth authentication endpoints.
        /// </summary>
        public IOAuth OAuth { get; }
    }

    /// <summary>
    /// OpenRouter API: OpenAI-compatible API with additional OpenRouter features<br/>
    /// <see href="https://openrouter.ai/docs">OpenRouter Documentation</see>
    /// </summary>
    public class OpenRouter : IOpenRouter
    {
        /// <summary>
        /// The main SDK Configuration.
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }
        /// <summary>
        /// The Beta sub-SDK.
        /// </summary>
        public IBeta Beta { get; private set; }
        /// <summary>
        /// The Analytics sub-SDK.
        /// </summary>
        public IAnalytics Analytics { get; private set; }
        /// <summary>
        /// The Chat sub-SDK.
        /// </summary>
        public IChat Chat { get; private set; }
        /// <summary>
        /// The Credits sub-SDK.
        /// </summary>
        public ICredits Credits { get; private set; }
        /// <summary>
        /// The Embeddings sub-SDK.
        /// </summary>
        public IEmbeddings Embeddings { get; private set; }
        /// <summary>
        /// The Generations sub-SDK.
        /// </summary>
        public IGenerations Generations { get; private set; }
        /// <summary>
        /// The AIModels sub-SDK.
        /// </summary>
        public IAIModels AIModels { get; private set; }
        /// <summary>
        /// The Endpoints sub-SDK.
        /// </summary>
        public IEndpoints Endpoints { get; private set; }
        /// <summary>
        /// The Providers sub-SDK.
        /// </summary>
        public IProviders Providers { get; private set; }
        /// <summary>
        /// The APIKeys sub-SDK.
        /// </summary>
        public IAPIKeys APIKeys { get; private set; }
        /// <summary>
        /// The Guardrails sub-SDK.
        /// </summary>
        public IGuardrails Guardrails { get; private set; }
        /// <summary>
        /// The OAuth sub-SDK.
        /// </summary>
        public IOAuth OAuth { get; private set; }

        /// <summary>
        /// Initializes a new instance of the SDK based on a <see cref="SDKConfig"/> configuration object.
        /// </summary>
        /// <param name="config">The SDK configuration object.</param>
        public OpenRouter(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Beta = new Beta(SDKConfiguration);

            Analytics = new Analytics(SDKConfiguration);

            Chat = new Chat(SDKConfiguration);

            Credits = new Credits(SDKConfiguration);

            Embeddings = new Embeddings(SDKConfiguration);

            Generations = new Generations(SDKConfiguration);

            AIModels = new AIModels(SDKConfiguration);

            Endpoints = new Endpoints(SDKConfiguration);

            Providers = new Providers(SDKConfiguration);

            APIKeys = new APIKeys(SDKConfiguration);

            Guardrails = new Guardrails(SDKConfiguration);

            OAuth = new OAuth(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="apiKey">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="apiKeySource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="httpReferer">
        /// The app identifier should be your app's URL and is used as the primary identifier for rankings.<br/>
        /// This is used to track API usage per application.
        /// </param>
        /// <param name="xTitle">The app display name allows you to customize how your app appears in OpenRouter's dashboard.</param>
        /// <param name="server">The server to use from the predefined server list.</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default OpenRouterHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        public OpenRouter(
            string? apiKey = null,
            Func<string>? apiKeySource = null,
            string? httpReferer = null,
            string? xTitle = null,
            SDKConfig.Server? server = null,
            string? serverUrl = null,
            Dictionary<string, string>? urlParams = null,
            IOpenRouterHttpClient? client = null,
            RetryConfig? retryConfig = null
        )
        {

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<OpenRouterSDK.Models.Components.Security>? _securitySource = null;

            if (apiKeySource != null)
            {
                _securitySource = () => new OpenRouterSDK.Models.Components.Security() { ApiKey = apiKeySource() };
            }
            else if (apiKey != null)
            {
                _securitySource = () => new OpenRouterSDK.Models.Components.Security() { ApiKey = apiKey };
            }

            SDKConfiguration = new SDKConfig(client) {
                HTTPReferer = httpReferer,
                XTitle = xTitle,
                ServerName = server,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Beta = new Beta(SDKConfiguration);

            Analytics = new Analytics(SDKConfiguration);

            Chat = new Chat(SDKConfiguration);

            Credits = new Credits(SDKConfiguration);

            Embeddings = new Embeddings(SDKConfiguration);

            Generations = new Generations(SDKConfiguration);

            AIModels = new AIModels(SDKConfiguration);

            Endpoints = new Endpoints(SDKConfiguration);

            Providers = new Providers(SDKConfiguration);

            APIKeys = new APIKeys(SDKConfiguration);

            Guardrails = new Guardrails(SDKConfiguration);

            OAuth = new OAuth(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        /// <summary>
        /// Builder class for constructing an instance of the SDK.
        /// </summary>
        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new OpenRouterHttpClient());

            public SDKBuilder()
            {
            }

            /// <summary>
            /// Overrides the default server by name.
            /// </summary>
            public SDKBuilder WithServer(SDKConfig.Server server)
            {
                _sdkConfig.ServerName = server;
                return this;
            }

            /// <summary>
            /// Overrides the default server URL for the SDK.
            /// </summary>
            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }
            /// <summary>
            /// Sets the HTTPReferer global parameter for the SDK.
            /// </summary>
            public SDKBuilder WithHTTPReferer(string httpReferer)
            {
                _sdkConfig.HTTPReferer = httpReferer;
                return this;
            }
            /// <summary>
            /// Sets the XTitle global parameter for the SDK.
            /// </summary>
            public SDKBuilder WithXTitle(string xTitle)
            {
                _sdkConfig.XTitle = xTitle;
                return this;
            }

            /// <summary>
            /// Sets the apiKeySource security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithApiKeySource(Func<string> apiKeySource)
            {
                _sdkConfig.SecuritySource = () => new OpenRouterSDK.Models.Components.Security() { ApiKey = apiKeySource() };
                return this;
            }

            /// <summary>
            /// Sets the apiKey security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithApiKey(string apiKey)
            {
                _sdkConfig.SecuritySource = () => new OpenRouterSDK.Models.Components.Security() { ApiKey = apiKey };
                return this;
            }

            /// <summary>
            /// Sets a custom HTTP client to be used by the SDK.
            /// </summary>
            public SDKBuilder WithClient(IOpenRouterHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            /// <summary>
            /// Sets the retry configuration for the SDK.
            /// </summary>
            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            /// <summary>
            /// Builds and returns the SDK instance.
            /// </summary>
            public OpenRouter Build()
            {
                return new OpenRouter(_sdkConfig);
            }
        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}