//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 4c14cb3d7817
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    public class BulkAssignKeysToGuardrailRequestBody
    {
        /// <summary>
        /// Array of API key hashes to assign to the guardrail.
        /// </summary>
        [JsonProperty("key_hashes")]
        public List<string> KeyHashes { get; set; } = default!;
    }
}