//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: adc46719a3ff
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Assignment result.
    /// </summary>
    public class BulkAssignKeysToGuardrailResponseBody
    {
        /// <summary>
        /// Number of keys successfully assigned.
        /// </summary>
        [JsonProperty("assigned_count")]
        public double AssignedCount { get; set; } = default!;
    }
}