//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 70d9bd98cec5
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    public class CallData
    {
        [JsonProperty("deadline")]
        public string Deadline { get; set; } = default!;

        [JsonProperty("fee_amount")]
        public string FeeAmount { get; set; } = default!;

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("operator")]
        public string Operator { get; set; } = default!;

        [JsonProperty("prefix")]
        public string Prefix { get; set; } = default!;

        [JsonProperty("recipient")]
        public string Recipient { get; set; } = default!;

        [JsonProperty("recipient_amount")]
        public string RecipientAmount { get; set; } = default!;

        [JsonProperty("recipient_currency")]
        public string RecipientCurrency { get; set; } = default!;

        [JsonProperty("refund_destination")]
        public string RefundDestination { get; set; } = default!;

        [JsonProperty("signature")]
        public string Signature { get; set; } = default!;
    }
}