//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 8a05c1d346f7
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ContentType
    {
        private ContentType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static ContentType Text
        {
            get {
                return new ContentType("text");
            }
        }

        public static ContentType ImageUrl
        {
            get {
                return new ContentType("image_url");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(ContentType v)
        {
            return v.Value;
        }
        public static ContentType FromString(string v)
        {
            switch (v)
            {
                case "text":
                    return Text;
                case "image_url":
                    return ImageUrl;
                default:
                    throw new ArgumentException("Invalid value for ContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(Content.ContentConverter))]
    public class Content
    {
        public Content(ContentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public ContentText? ContentText { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ContentImageURL? ContentImageURL { get; set; }

        public ContentType Type { get; set; }

        public static Content CreateText(ContentText text)
        {
            ContentType typ = ContentType.Text;
            string typStr = ContentType.Text.ToString();
            text.Type = TypeTextExtension.ToEnum(ContentType.Text.ToString());
            Content res = new Content(typ);
            res.ContentText = text;
            return res;
        }

        public static Content CreateImageUrl(ContentImageURL imageURL)
        {
            ContentType typ = ContentType.ImageUrl;
            string typStr = ContentType.ImageUrl.ToString();
            imageURL.Type = TypeImageURLExtension.ToEnum(ContentType.ImageUrl.ToString());
            Content res = new Content(typ);
            res.ContentImageURL = imageURL;
            return res;
        }

        public class ContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Content);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue("type")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == ContentType.Text.ToString())
                {
                    ContentText contentText = ResponseBodyDeserializer.DeserializeNotNull<ContentText>(jo.ToString());
                    return CreateText(contentText);
                }
                if (discriminator == ContentType.ImageUrl.ToString())
                {
                    ContentImageURL contentImageURL = ResponseBodyDeserializer.DeserializeNotNull<ContentImageURL>(jo.ToString());
                    return CreateImageUrl(contentImageURL);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Content res = (Content)value;

                if (res.ContentText != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ContentText));
                    return;
                }

                if (res.ContentImageURL != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ContentImageURL));
                    return;
                }
            }
        }
    }
}