//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 1cfa7466b40f
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class CreateAuthKeysCodeRequestBody
    {
        /// <summary>
        /// The callback URL to redirect to after authorization. Note, only https URLs on ports 443 and 3000 are allowed.
        /// </summary>
        [JsonProperty("callback_url")]
        public string CallbackUrl { get; set; } = default!;

        /// <summary>
        /// PKCE code challenge for enhanced security.
        /// </summary>
        [JsonProperty("code_challenge")]
        public string? CodeChallenge { get; set; }

        /// <summary>
        /// The method used to generate the code challenge.
        /// </summary>
        [JsonProperty("code_challenge_method")]
        public CreateAuthKeysCodeCodeChallengeMethod? CodeChallengeMethod { get; set; }

        /// <summary>
        /// Credit limit for the API key to be created.
        /// </summary>
        [JsonProperty("limit")]
        public double? Limit { get; set; }

        /// <summary>
        /// Optional expiration time for the API key to be created.
        /// </summary>
        [JsonProperty("expires_at")]
        public DateTime? ExpiresAt { get; set; } = null;

        /// <summary>
        /// Optional custom label for the API key. Defaults to the app name if not provided.
        /// </summary>
        [JsonProperty("key_label")]
        public string? KeyLabel { get; set; }

        /// <summary>
        /// Optional credit limit reset interval. When set, the credit limit resets on this interval.
        /// </summary>
        [JsonProperty("usage_limit_type")]
        public UsageLimitType? UsageLimitType { get; set; }
    }
}