//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 925b0c2c6241
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Interval at which the limit resets (daily, weekly, monthly).
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CreateGuardrailResetIntervalResponse : IEquatable<CreateGuardrailResetIntervalResponse>
    {
        public static readonly CreateGuardrailResetIntervalResponse Daily = new CreateGuardrailResetIntervalResponse("daily");
        public static readonly CreateGuardrailResetIntervalResponse Weekly = new CreateGuardrailResetIntervalResponse("weekly");
        public static readonly CreateGuardrailResetIntervalResponse Monthly = new CreateGuardrailResetIntervalResponse("monthly");

        private static readonly Dictionary<string, CreateGuardrailResetIntervalResponse> _knownValues =
            new Dictionary<string, CreateGuardrailResetIntervalResponse>() {
                ["daily"] = Daily,
                ["weekly"] = Weekly,
                ["monthly"] = Monthly
            };

        private static readonly ConcurrentDictionary<string, CreateGuardrailResetIntervalResponse> _values =
            new ConcurrentDictionary<string, CreateGuardrailResetIntervalResponse>(_knownValues);

        private CreateGuardrailResetIntervalResponse(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CreateGuardrailResetIntervalResponse Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new CreateGuardrailResetIntervalResponse(value));
        }

        public static implicit operator CreateGuardrailResetIntervalResponse(string value) => Of(value);
        public static implicit operator string(CreateGuardrailResetIntervalResponse createguardrailresetintervalresponse) => createguardrailresetintervalresponse.Value;

        public static CreateGuardrailResetIntervalResponse[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CreateGuardrailResetIntervalResponse);

        public bool Equals(CreateGuardrailResetIntervalResponse? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}