//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: c878e4840fe1
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Guardrail created successfully.
    /// </summary>
    public class CreateGuardrailResponseBody
    {
        /// <summary>
        /// The created guardrail.
        /// </summary>
        [JsonProperty("data")]
        public CreateGuardrailData Data { get; set; } = default!;
    }
}