//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: db92f9667e8d
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    public class CreateEmbeddingsData
    {
        [JsonProperty("object")]
        public ObjectEmbedding Object { get; set; } = default!;

        [JsonProperty("embedding", NullValueHandling = NullValueHandling.Include)]
        public Embedding Embedding { get; set; } = default!;

        [JsonProperty("index")]
        public double? Index { get; set; }
    }
}