//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 40b433a2bf93
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class CreateGuardrailRequestBody
    {
        /// <summary>
        /// Name for the new guardrail.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Description of the guardrail.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// Spending limit in USD.
        /// </summary>
        [JsonProperty("limit_usd")]
        public double? LimitUsd { get; set; } = null;

        /// <summary>
        /// Interval at which the limit resets (daily, weekly, monthly).
        /// </summary>
        [JsonProperty("reset_interval")]
        public CreateGuardrailResetIntervalRequest? ResetInterval { get; set; } = null;

        /// <summary>
        /// List of allowed provider IDs.
        /// </summary>
        [JsonProperty("allowed_providers")]
        public List<string>? AllowedProviders { get; set; } = null;

        /// <summary>
        /// Array of model identifiers (slug or canonical_slug accepted).
        /// </summary>
        [JsonProperty("allowed_models")]
        public List<string>? AllowedModels { get; set; } = null;

        /// <summary>
        /// Whether to enforce zero data retention.
        /// </summary>
        [JsonProperty("enforce_zdr")]
        public bool? EnforceZdr { get; set; } = null;
    }
}