//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 9d7ef7b42a19
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class EmbeddingType
    {
        private EmbeddingType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static EmbeddingType ArrayOfNumber
        {
            get {
                return new EmbeddingType("arrayOfNumber");
            }
        }

        public static EmbeddingType Str
        {
            get {
                return new EmbeddingType("str");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(EmbeddingType v)
        {
            return v.Value;
        }
        public static EmbeddingType FromString(string v)
        {
            switch (v)
            {
                case "arrayOfNumber":
                    return ArrayOfNumber;
                case "str":
                    return Str;
                default:
                    throw new ArgumentException("Invalid value for EmbeddingType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((EmbeddingType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(Embedding.EmbeddingConverter))]
    public class Embedding
    {
        public Embedding(EmbeddingType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public List<double>? ArrayOfNumber { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        public EmbeddingType Type { get; set; }
        public static Embedding CreateArrayOfNumber(List<double> arrayOfNumber)
        {
            EmbeddingType typ = EmbeddingType.ArrayOfNumber;

            Embedding res = new Embedding(typ);
            res.ArrayOfNumber = arrayOfNumber;
            return res;
        }
        public static Embedding CreateStr(string str)
        {
            EmbeddingType typ = EmbeddingType.Str;

            Embedding res = new Embedding(typ);
            res.Str = str;
            return res;
        }

        public class EmbeddingConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Embedding);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Embedding(EmbeddingType.ArrayOfNumber) {
                        ArrayOfNumber = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<double>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<double>), new Embedding(EmbeddingType.ArrayOfNumber), "ArrayOfNumber"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"')
                {
                    return new Embedding(EmbeddingType.Str) {
                        Str = json[1.. ^ 1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Embedding res = (Embedding)value;

                if (res.ArrayOfNumber != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfNumber));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
            }
        }
    }
}