//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: f4b52f56e7c0
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;

    public class GetCreditsData
    {
        /// <summary>
        /// Total credits purchased.
        /// </summary>
        [JsonProperty("total_credits")]
        public double TotalCredits { get; set; } = default!;

        /// <summary>
        /// Total credits used.
        /// </summary>
        [JsonProperty("total_usage")]
        public double TotalUsage { get; set; } = default!;
    }
}