//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 8c1ed41ed043
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Total credits purchased and used.
    /// </summary>
    public class GetCreditsResponseBody
    {
        [JsonProperty("data")]
        public GetCreditsData Data { get; set; } = default!;
    }
}