//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 61b475a55711
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// API key details.
    /// </summary>
    public class GetKeyResponseBody
    {
        /// <summary>
        /// The API key information.
        /// </summary>
        [JsonProperty("data")]
        public GetKeyData Data { get; set; } = default!;
    }
}