//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: baaff250b1f8
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Components;
    using OpenRouterSDK.Utils;

    public class GetModelsResponse
    {
        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// Returns a list of models or RSS feed.
        /// </summary>
        public ModelsListResponse? ModelsListResponse { get; set; }
    }
}