//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: e3077f140398
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class GetModelsRequest
    {
        /// <summary>
        /// The app identifier should be your app's URL and is used as the primary identifier for rankings.<br/>
        /// This is used to track API usage per application.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=HTTP-Referer")]
        public string? HTTPReferer { get; set; }

        /// <summary>
        /// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Title")]
        public string? XTitle { get; set; }

        /// <summary>
        /// Filter models by use case category.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=category")]
        public Category? Category { get; set; }

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=supported_parameters")]
        public string? SupportedParameters { get; set; }
    }
}