//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 4186a5b76d35
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using OpenRouterSDK.Utils;

    public class GetUserActivityRequest
    {
        /// <summary>
        /// The app identifier should be your app's URL and is used as the primary identifier for rankings.<br/>
        /// This is used to track API usage per application.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=HTTP-Referer")]
        public string? HTTPReferer { get; set; }

        /// <summary>
        /// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Title")]
        public string? XTitle { get; set; }

        /// <summary>
        /// Filter by a single UTC date in the last 30 days (YYYY-MM-DD format).
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=date")]
        public string? Date { get; set; }
    }
}