//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: f3b5a6b2d214
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Interval at which the limit resets (daily, weekly, monthly).
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ListGuardrailsResetInterval : IEquatable<ListGuardrailsResetInterval>
    {
        public static readonly ListGuardrailsResetInterval Daily = new ListGuardrailsResetInterval("daily");
        public static readonly ListGuardrailsResetInterval Weekly = new ListGuardrailsResetInterval("weekly");
        public static readonly ListGuardrailsResetInterval Monthly = new ListGuardrailsResetInterval("monthly");

        private static readonly Dictionary<string, ListGuardrailsResetInterval> _knownValues =
            new Dictionary<string, ListGuardrailsResetInterval>() {
                ["daily"] = Daily,
                ["weekly"] = Weekly,
                ["monthly"] = Monthly
            };

        private static readonly ConcurrentDictionary<string, ListGuardrailsResetInterval> _values =
            new ConcurrentDictionary<string, ListGuardrailsResetInterval>(_knownValues);

        private ListGuardrailsResetInterval(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ListGuardrailsResetInterval Of(string value)
        {
            return _values.GetOrAdd(value,
                                    _ => new ListGuardrailsResetInterval(value));
        }

        public static implicit operator ListGuardrailsResetInterval(string value) => Of(value);
        public static implicit operator string(ListGuardrailsResetInterval listguardrailsresetinterval) => listguardrailsresetinterval.Value;

        public static ListGuardrailsResetInterval[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ListGuardrailsResetInterval);

        public bool Equals(ListGuardrailsResetInterval? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}