//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 1c1a13072f95
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using OpenRouterSDK.Utils;

    public class ListKeyAssignmentsRequest
    {
        /// <summary>
        /// The app identifier should be your app's URL and is used as the primary identifier for rankings.<br/>
        /// This is used to track API usage per application.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=HTTP-Referer")]
        public string? HTTPReferer { get; set; }

        /// <summary>
        /// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Title")]
        public string? XTitle { get; set; }

        /// <summary>
        /// Number of records to skip for pagination.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")]
        public string? Offset { get; set; }

        /// <summary>
        /// Maximum number of records to return (max 100).
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public string? Limit { get; set; }
    }
}