//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: b6b082548f89
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// List of guardrails.
    /// </summary>
    public class ListGuardrailsResponseBody
    {
        /// <summary>
        /// List of guardrails.
        /// </summary>
        [JsonProperty("data")]
        public List<ListGuardrailsData> Data { get; set; } = default!;

        /// <summary>
        /// Total number of guardrails.
        /// </summary>
        [JsonProperty("total_count")]
        public double TotalCount { get; set; } = default!;
    }
}