//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: ea042cfce826
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Utils;
    using System;

    public enum TypeImageURL
    {
        [JsonProperty("image_url")] ImageUrl,
    }

    public static class TypeImageURLExtension
    {
        public static string Value(this TypeImageURL value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TypeImageURL ToEnum(this string value)
        {
            foreach (var field in typeof(TypeImageURL).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TypeImageURL)
                    {
                        return (TypeImageURL)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TypeImageURL");
        }
    }
}