//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: acef9286feb2
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// Guardrail updated successfully.
    /// </summary>
    public class UpdateGuardrailResponseBody
    {
        /// <summary>
        /// The updated guardrail.
        /// </summary>
        [JsonProperty("data")]
        public UpdateGuardrailData Data { get; set; } = default!;
    }
}