//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: abc0932d743d
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    /// <summary>
    /// API key updated successfully.
    /// </summary>
    public class UpdateKeysResponseBody
    {
        /// <summary>
        /// The updated API key information.
        /// </summary>
        [JsonProperty("data")]
        public UpdateKeysData Data { get; set; } = default!;
    }
}