//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 845c9bd559d5
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;

    public class UpdateKeysRequest
    {
        /// <summary>
        /// The app identifier should be your app's URL and is used as the primary identifier for rankings.<br/>
        /// This is used to track API usage per application.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=HTTP-Referer")]
        public string? HTTPReferer { get; set; }

        /// <summary>
        /// The app display name allows you to customize how your app appears in OpenRouter's dashboard.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=X-Title")]
        public string? XTitle { get; set; }

        /// <summary>
        /// The hash identifier of the API key to update.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=hash")]
        public string Hash { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public UpdateKeysRequestBody RequestBody { get; set; } = default!;
    }
}