//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 601e81d8ba24
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OpenRouterSDK.Models.Requests
{
    using Newtonsoft.Json;
    using OpenRouterSDK.Models.Requests;
    using OpenRouterSDK.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class UpdateKeysRequestBody
    {
        /// <summary>
        /// New name for the API key.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Whether to disable the API key.
        /// </summary>
        [JsonProperty("disabled")]
        public bool? Disabled { get; set; }

        /// <summary>
        /// New spending limit for the API key in USD.
        /// </summary>
        [JsonProperty("limit")]
        public double? Limit { get; set; } = null;

        /// <summary>
        /// New limit reset type for the API key (daily, weekly, monthly, or null for no reset). Resets happen automatically at midnight UTC, and weeks are Monday through Sunday.
        /// </summary>
        [JsonProperty("limit_reset")]
        public UpdateKeysLimitReset? LimitReset { get; set; } = null;

        /// <summary>
        /// Whether to include BYOK usage in the limit.
        /// </summary>
        [JsonProperty("include_byok_in_limit")]
        public bool? IncludeByokInLimit { get; set; }
    }
}